package com.dcenhance.xtream_player.dexcoreupdate;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Build;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.security.KeyFactory;
import java.security.MessageDigest;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;
import android.util.Base64;
import java.util.HashSet;
import java.util.Locale;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.lang.ref.WeakReference;

/** Generated by DEXCORE. It only installs verified Archive APKs via Android's installer. */
public final class DceArchiveUpdates {
  // Bootstrap routing is reconstructed only at runtime. This removes the server and
  // private control path from Java/Dex string pools; it is deterrence, not a secret.
  private static final int ENDPOINT_SEED = 176193030;
  private static final int[] ENDPOINT_DATA = new int[]{197, 92, 19, 234, 66, 230, 164, 65, 145, 179, 138, 236, 145, 101, 253, 181, 88, 21, 18, 4, 181, 95, 181, 93, 234, 77, 208, 51, 251, 55, 203, 207, 187, 173, 168, 74, 35, 19, 193, 107, 118, 4, 124, 13, 120, 212, 216, 5, 114, 75, 231, 111, 130, 184, 201, 187, 138, 181, 111, 150, 200, 128, 166, 104, 135, 27, 200, 180};
  private static final int CONTROL_SEED = 2058449022;
  private static final int[] CONTROL_DATA = new int[]{234, 63, 86, 252, 189, 241, 145, 136, 108, 100, 232, 27, 227, 223, 131, 39, 35, 213, 98, 3, 44, 144, 155, 153, 232, 40, 179, 43, 85, 105, 214, 122, 128, 108, 54, 68, 140, 70, 122, 185, 76, 216, 151, 39, 226, 44, 110, 141, 1, 34, 10};
  private static final String PINNED_UPDATE_PUBLIC_KEY = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGL5uJdF7s7yricM8KMXOpZXiAn89f5u9u8kVPMbGGalw3MHJ8AeWG+t4n3UgmUaV26+B0lxwkzIdGg4pN+/EjA==";
  private static final int MAX_DESCRIPTOR_BYTES = 64 * 1024;
  private static final long MAX_APK_BYTES = 4294967296L;
  static final String PREFERENCES = "dexcore_archive_updates";
  static final String AUTO_DOWNLOAD_UPDATES = "auto_download_verified_updates";
  // "Not now" is a visible third choice with a hard budget: three postponements
  // per update version, then the notice exposes no dismissal route at all. The
  // budget is per versionCode, so a newer release grants a fresh allowance.
  static final int NOT_NOW_LIMIT = 3;
  static final String NOT_NOW_PREFIX = "not_now_postponements_";
  // Kept only for people who selected the legacy, dialog-suppression action.
  static final String LEGACY_SUPPRESS_DIALOGS = "suppress_update_dialogs";
  // Additional content (drawing packs, ROM sets, media bundles) ships through the
  // same signed descriptor as the APK, so a data-only change can be announced
  // without a new release. The client only learns the newest acknowledged
  // revision, so identical bytes never prompt twice and new bytes always do.
  static final String SEEN_CATALOG_REVISION = "seen_catalog_revision";
  static final String CONTENT_READY_ACTION = ".dexcoreupdate.CONTENT_READY";
  static final String CATALOG_NOT_NOW_PREFIX = "not_now_catalog_";
  static final String CONTENT_DIRECTORY = "dexcore-archive-content";
  private static final int MAX_CATALOG_FILES = 64;
  private static final long MAX_CATALOG_TOTAL_BYTES = 68719476736L;
  // Every release carries a categorized changelog in the 20 app languages, generated
  // by the archive and signed into the descriptor. The bounds below mirror the
  // publisher: a block the client would refuse must never be signed.
  private static final int MAX_CHANGELOG_JSON_BYTES = 24576;
  private static final int MAX_CHANGELOG_TABLES = 21;
  private static final int MAX_CHANGELOG_CATEGORIES = 12;
  private static final int MAX_CHANGELOG_ENTRIES = 12;
  private static final int MAX_CHANGELOG_ENTRY_CHARS = 240;
  private static final int MAX_CHANGELOG_LABEL_CHARS = 120;
  // The data (content) changelog is a separate, smaller block inside the catalog.
  private static final int MAX_CONTENT_CHANGELOG_JSON_BYTES = 16384;
  private static final long FOREGROUND_POLL_INTERVAL_MS = 30_000L;
  // A visible update Activity receives determinate byte progress at a bounded
  // rate so a slow link and a fast link both look smooth without flooding the
  // main thread with updates.
  private static final long PROGRESS_STEP_BYTES = 524_288L;
  private static final long PROGRESS_INTERVAL_MS = 300L;
  // The verified transfer outlives any single notice: the byte counters and the
  // currently attached listener are static, so a re-opened dialog (or a return
  // from the background) resumes the live bar instead of restarting blindly.
  private static volatile WeakReference<DownloadProgress> ACTIVE_PROGRESS = new WeakReference<>(null);
  private static volatile long PROGRESS_DOWNLOADED;
  private static volatile long PROGRESS_TOTAL;
  private static final ExecutorService EXECUTOR = Executors.newSingleThreadExecutor();
  private static final AtomicBoolean DOWNLOAD_ACTIVE = new AtomicBoolean(false);
  private static final AtomicBoolean CHECK_ACTIVE = new AtomicBoolean(false);
  private static final AtomicBoolean LIFECYCLE_INSTALLED = new AtomicBoolean(false);
  private static final AtomicInteger RESUMED_ACTIVITIES = new AtomicInteger(0);
  private static final android.os.Handler MAIN = new android.os.Handler(android.os.Looper.getMainLooper());
  private static volatile WeakReference<Activity> FOREGROUND_ACTIVITY = new WeakReference<>(null);
  private static final Runnable FOREGROUND_POLL = new Runnable() {
    @Override public void run() {
      Activity activity = FOREGROUND_ACTIVITY.get();
      if (RESUMED_ACTIVITIES.get() <= 0 || activity == null || activity.isFinishing()) return;
      requestCheck(activity);
      MAIN.postDelayed(this, FOREGROUND_POLL_INTERVAL_MS);
    }
  };
  private static final Pattern UTC_RFC3339 = Pattern.compile("^([0-9]{4})-([0-9]{2})-([0-9]{2})T([0-9]{2}):([0-9]{2}):([0-9]{2})(?:[.]([0-9]{1,9}))?Z$");
  private DceArchiveUpdates() {}

  public static void check(Activity activity) {
    if (activity == null || activity.isFinishing()) return;
    installForegroundChecks(activity);
    requestCheck(activity);
  }

  private static void installForegroundChecks(Activity seed) {
    if (!LIFECYCLE_INSTALLED.compareAndSet(false, true)) return;
    seed.getApplication().registerActivityLifecycleCallbacks(new android.app.Application.ActivityLifecycleCallbacks() {
      @Override public void onActivityResumed(Activity activity) {
        if (activity instanceof DceArchiveUpdateActivity) return;
        FOREGROUND_ACTIVITY = new WeakReference<>(activity);
        RESUMED_ACTIVITIES.incrementAndGet();
        MAIN.removeCallbacks(FOREGROUND_POLL);
        requestCheck(activity);
        MAIN.postDelayed(FOREGROUND_POLL, FOREGROUND_POLL_INTERVAL_MS);
      }
      @Override public void onActivityPaused(Activity activity) {
        if (activity instanceof DceArchiveUpdateActivity) return;
        int remaining = RESUMED_ACTIVITIES.decrementAndGet();
        if (remaining <= 0) { RESUMED_ACTIVITIES.set(0); MAIN.removeCallbacks(FOREGROUND_POLL); }
      }
      @Override public void onActivityDestroyed(Activity activity) {
        Activity current = FOREGROUND_ACTIVITY.get();
        if (current == activity) FOREGROUND_ACTIVITY = new WeakReference<>(null);
      }
      @Override public void onActivityCreated(Activity activity, android.os.Bundle state) {}
      @Override public void onActivityStarted(Activity activity) {}
      @Override public void onActivityStopped(Activity activity) {}
      @Override public void onActivitySaveInstanceState(Activity activity, android.os.Bundle state) {}
    });
  }

  public static void checkNow(Activity activity) { requestCheck(activity, true); }

  private static void requestCheck(Activity activity) { requestCheck(activity, false); }

  private static void checkMessage(Activity activity, String message) {
    activity.runOnUiThread(() -> android.widget.Toast.makeText(activity, message, android.widget.Toast.LENGTH_LONG).show());
  }

  private static void requestCheck(Activity activity, boolean manual) {
    if (activity == null || activity.isFinishing() || !CHECK_ACTIVE.compareAndSet(false, true)) return;
    EXECUTOR.execute(() -> {
      try {
        URL endpointUrl = endpointUrl();
        String controlUrl = new URL(endpointUrl.getProtocol(), endpointUrl.getHost(), endpointUrl.getPort(), concealed(CONTROL_DATA, CONTROL_SEED)).toString();
        JSONObject delivery = new JSONObject(readUrl(controlUrl));
        Object enabled = delivery.opt("futureArchiveUpdatesEnabled");
        if (!(enabled instanceof Boolean) || !((Boolean) enabled)) { if (manual) checkMessage(activity, "Updates are paused by the owner."); return; }
        // Debug and release installations own separate update lanes: a debug build
        // never receives a release descriptor and vice versa.
        JSONObject update = verifySignedDescriptor(readUrl(laneEndpointUrl(activity).toString()));
        if (!validDescriptor(activity, update)) { if (manual) checkMessage(activity, "No verified update is available. Try again later."); return; }
        rememberNoticePalette(update);
        String expectedPackage = requireJsonString(update, "expectedPackageName");
        if (!expectedPackage.equals(activity.getPackageName())) return;
        boolean appUpdate = requirePositiveLong(update, "versionCode") > installedVersion(activity);
        // A signed descriptor can announce a release, new content, or both. Content
        // is never downloaded silently: the app owns what it does with the bytes.
        if (manual && catalogFor(update) != null && !catalogContentVerified(activity, update))
          activity.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE).edit().remove(SEEN_CATALOG_REVISION).apply();
        boolean dataUpdate = catalogUpdateAvailable(activity, update);
        if (!appUpdate && !dataUpdate) { if (manual) checkMessage(activity, "App and content are up to date."); return; }
        boolean required = isRequiredUpdate(activity, update) || (dataUpdate && isRequiredCatalog(update));
        android.content.SharedPreferences preferences = activity.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE);
        boolean autoDownload = preferences.getBoolean(AUTO_DOWNLOAD_UPDATES, false);
        // A legacy "don't ask again" hid the old dialog permanently. Clear it once
        // so upgraded clients can present the replacement automatic-update choice.
        if (preferences.getBoolean(LEGACY_SUPPRESS_DIALOGS, false)) preferences.edit().remove(LEGACY_SUPPRESS_DIALOGS).apply();
        if (!appUpdate) activity.runOnUiThread(() -> openUpdateActivity(activity, update, false));
        else if (manual || dataUpdate || required || !autoDownload) activity.runOnUiThread(() -> openUpdateActivity(activity, update, autoDownload));
        else downloadAndInstall(activity, update);
      } catch (Exception ignored) { if (manual) checkMessage(activity, "Could not check updates. Check your connection and try again."); }
      finally { CHECK_ACTIVE.set(false); }
    });
  }

  /** Determinate download progress for a visible update Activity. */
  public interface DownloadProgress {
    void onBytes(long downloaded, long totalBytes);
    void onVerifying();
  }

  public static void downloadAndInstall(Activity activity, JSONObject update) { downloadAndInstall(activity, update, null); }

  public static void downloadAndInstall(Activity activity, JSONObject update, DownloadProgress progress) {
    if (activity == null || activity.isFinishing() || !validDescriptor(activity, update)) { notifyDownloadFailure(activity, "Update verification failed. Try again."); return; }
    if (!DOWNLOAD_ACTIVE.compareAndSet(false, true)) {
      // A verified transfer is already running (for example after the notice was
      // closed and re-opened): re-attach to it instead of reporting a failure.
      if (progress != null) attachProgress(activity, progress);
      else notifyDownloadFailure(activity, "An update download is already running. Try again shortly.");
      return;
    }
    final String snapshot = update.toString();
    final DownloadProgress listener = progress;
    ACTIVE_PROGRESS = new WeakReference<>(progress);
    EXECUTOR.execute(() -> {
      try {
        File apk = downloadVerifiedApk(activity, new JSONObject(snapshot), listener);
        if (apk == null) throw new java.io.IOException("Verified download unavailable");
        activity.runOnUiThread(() -> {
          if (requestAndroidInstall(activity, apk)) notifyInstallerStarted(activity);
          else notifyDownloadFailure(activity, "Android could not open the installer. Try again.");
        });
      } catch (Exception ignored) { notifyDownloadFailure(activity, "Download or verification failed. Try again."); }
      finally { DOWNLOAD_ACTIVE.set(false); ACTIVE_PROGRESS = new WeakReference<>(null); }
    });
  }

  private static boolean validDescriptor(Context context, JSONObject update) {
    if (update == null) return false;
    try {
      URL endpoint = endpointUrl();
      URL download = new URL(requireJsonString(update, "downloadUrl"));
      long size = requirePositiveLong(update, "sizeBytes");
      String expectedPackage = requireJsonString(update, "expectedPackageName");
      return expectedPackage.length() > 0
          && expectedPackage.equals(context.getPackageName())
          && expectedPackage.equals(requireJsonString(update, "packageName"))
          && requirePositiveLong(update, "versionCode") > 0L
          && requireJsonString(update, "versionName").length() > 0
          && requireJsonString(update, "sha256").matches("[0-9a-fA-F]{64}")
          && size > 0L && size <= MAX_APK_BYTES
          && strictUpdatePolicy(requireJsonObject(update, "updatePolicy")) != null
          && strictSignerArray(update)
          && sameArchiveOrigin(endpoint, download)
          && download.getPath().startsWith(laneDirectoryPath(context));
    } catch (Exception invalid) { return false; }
  }

  // The archive owner can pin the notice colour per app in the signed descriptor, so a
  // wrong, stale or undetectable colour is correctable without rebuilding the app. The
  // pinned value is applied only when it is an opaque six-digit colour.
  private static volatile int NOTICE_ACCENT = 0;

  /** Owner-pinned notice colour from the last verified descriptor, or 0. */
  static int noticeAccent() { return NOTICE_ACCENT; }

  static void rememberNoticePalette(JSONObject update) {
    int parsed = 0;
    try {
      JSONObject palette = update == null ? null : update.optJSONObject("noticePalette");
      Object value = palette == null ? null : palette.opt("accent");
      if (value instanceof String && ((String) value).matches("#[0-9a-fA-F]{6}")) {
        parsed = android.graphics.Color.parseColor((String) value) | 0xFF000000;
      }
    } catch (Exception ignored) { parsed = 0; }
    NOTICE_ACCENT = parsed;
  }

  private static final class UpdatePolicy {
    final String mode; final Long minimumVersionCode; final Long expiresAtMillis;
    UpdatePolicy(String mode, Long minimumVersionCode, Long expiresAtMillis) { this.mode = mode; this.minimumVersionCode = minimumVersionCode; this.expiresAtMillis = expiresAtMillis; }
  }

  private static UpdatePolicy strictUpdatePolicy(JSONObject policy) throws Exception {
    String mode = requireJsonString(policy, "mode");
    if (!("optional".equals(mode) || "recommended".equals(mode) || "required".equals(mode))) throw new java.io.IOException("Invalid update mode");
    Long minimum = optionalNonNegativeLong(policy, "minimumVersionCode");
    Long expiry = optionalUtcExpiration(policy, "expiresAt");
    return new UpdatePolicy(mode, minimum, expiry);
  }

  static boolean isRequiredUpdate(Context context, JSONObject update) {
    try {
      UpdatePolicy policy = strictUpdatePolicy(requireJsonObject(update, "updatePolicy"));
      if (!"required".equals(policy.mode)) return false;
      if (policy.minimumVersionCode != null && installedVersion(context) >= policy.minimumVersionCode) return false;
      if (policy.expiresAtMillis != null && System.currentTimeMillis() >= policy.expiresAtMillis) return false;
      return true;
    } catch (Exception invalid) { return false; }
  }

  // ---- additional content (catalog) delivery ------------------------------

  /** The app-owned content block of a signed descriptor, or null when invalid. */
  static JSONObject catalogFor(JSONObject update) { return validCatalog(update); }

  /** Advertised content bytes, or 0 when the descriptor carries no valid content. */
  static long catalogTotalBytes(JSONObject update) {
    try { return requirePositiveLong(validCatalog(update), "totalSizeBytes"); } catch (Exception invalid) { return 0L; }
  }

  /** Short, locale-neutral summary of the pending content for the notice body. */
  static String catalogSummaryLabel(JSONObject update) {
    try {
      JSONObject catalog = validCatalog(update);
      if (catalog == null) return "";
      JSONArray files = catalog.getJSONArray("files");
      String first = requireJsonString(files.getJSONObject(0), "label");
      return files.length() == 1 ? first : first + " +" + (files.length() - 1);
    } catch (Exception invalid) { return ""; }
  }

  /** Public archive page of this app, used when the bytes are gated. */
  public static String archivePageUrl() {
    try {
      URL endpoint = endpointUrl();
      String path = endpoint.getPath();
      return endpoint.getProtocol() + "://" + endpoint.getHost() + path.substring(0, path.lastIndexOf('/') + 1);
    } catch (Exception invalid) { return null; }
  }

  /** One localized view of the signed per-version changelog. */
  static final class Changelog {
    final String heading; final String sizeLine; final String larger; final String smaller; final String same;
    final String[] labels; final String[][] notes;
    Changelog(String heading, String sizeLine, String larger, String smaller, String same, String[] labels, String[][] notes) {
      this.heading = heading; this.sizeLine = sizeLine; this.larger = larger; this.smaller = smaller; this.same = same;
      this.labels = labels; this.notes = notes;
    }
    boolean isEmpty() {
      for (String[] group : notes) if (group.length > 0) return false;
      return true;
    }
    int entryCount() { int total = 0; for (String[] group : notes) total += group.length; return total; }
  }

  // The archive generates every release note in the 20 app languages, so the notice
  // only has to pick the table the device asks for. A device language the archive
  // does not ship falls back to the language table and then to English.
  private static String[] changelogLanguageKeys(Locale locale) {
    String language = locale == null ? "en" : locale.getLanguage().toLowerCase(Locale.US);
    String region = locale == null ? "" : locale.getCountry().toUpperCase(Locale.US);
    if (language.isEmpty()) language = "en";
    if ("zh".equals(language) && ("TW".equals(region) || "HK".equals(region) || "MO".equals(region))) {
      return new String[] { "zh-Hant", "zh", "en" };
    }
    return new String[] { language, "en" };
  }

  /**
   * The changelog block of exactly this release, localized for the device locale,
   * or null when the descriptor carries none or the block is not trustworthy.
   */
  static Changelog changelogFor(JSONObject update, Locale locale) {
    try {
      Object raw = update == null ? null : update.opt("changelog");
      if (!(raw instanceof JSONObject)) return null;
      JSONObject block = (JSONObject) raw;
      if (block.toString().length() > MAX_CHANGELOG_JSON_BYTES) return null;
      // The notes describe one release: a block for another versionCode is stale.
      Object code = block.get("versionCode");
      if (!(code instanceof Number) || ((Number) code).longValue() != requirePositiveLong(update, "versionCode")) return null;
      JSONArray categories = block.getJSONArray("categories");
      if (categories.length() == 0 || categories.length() > MAX_CHANGELOG_CATEGORIES) return null;
      String[] names = new String[categories.length()];
      for (int index = 0; index < names.length; index++) {
        Object value = categories.get(index);
        if (!(value instanceof String) || ((String) value).isEmpty()) return null;
        names[index] = (String) value;
      }
      JSONObject notices = block.getJSONObject("notices");
      if (notices.length() == 0 || notices.length() > MAX_CHANGELOG_TABLES) return null;
      JSONObject notice = null;
      for (String key : changelogLanguageKeys(locale)) {
        Object candidate = notices.opt(key);
        if (candidate instanceof JSONObject) { notice = (JSONObject) candidate; break; }
      }
      if (notice == null) return null;
      String heading = requireBoundedText(notice, "heading", MAX_CHANGELOG_LABEL_CHARS);
      String sizeLine = requireBoundedText(notice, "sizeLine", MAX_CHANGELOG_LABEL_CHARS);
      String larger = requireBoundedText(notice, "larger", MAX_CHANGELOG_LABEL_CHARS);
      String smaller = requireBoundedText(notice, "smaller", MAX_CHANGELOG_LABEL_CHARS);
      String same = requireBoundedText(notice, "same", MAX_CHANGELOG_LABEL_CHARS);
      JSONObject labels = notice.getJSONObject("labels");
      JSONObject notes = notice.getJSONObject("notes");
      String[] labelValues = new String[names.length];
      String[][] noteValues = new String[names.length][];
      int total = 0;
      for (int index = 0; index < names.length; index++) {
        String category = names[index];
        labelValues[index] = requireBoundedText(labels, category, MAX_CHANGELOG_LABEL_CHARS);
        JSONArray values = notes.getJSONArray(category);
        if (values.length() == 0 || values.length() > MAX_CHANGELOG_ENTRIES) return null;
        String[] entries = new String[values.length()];
        for (int entry = 0; entry < entries.length; entry++) {
          Object value = values.get(entry);
          if (!(value instanceof String)) return null;
          String text = ((String) value).trim();
          if (text.isEmpty() || text.length() > MAX_CHANGELOG_ENTRY_CHARS) return null;
          entries[entry] = text;
        }
        noteValues[index] = entries;
        total += entries.length;
      }
      if (total == 0) return null;
      return new Changelog(heading, sizeLine, larger, smaller, same, labelValues, noteValues);
    } catch (Exception invalid) { return null; }
  }

  private static String requireBoundedText(JSONObject source, String key, int limit) throws Exception {
    String value = requireJsonString(source, key).trim();
    if (value.isEmpty() || value.length() > limit) throw new java.io.IOException("Invalid changelog text");
    return value;
  }

  /** One localized view of the signed data (content) changelog of this release. */
  static final class DataChangelog {
    final String heading; final String versionLine; final String verifiedLine;
    final String dataVersion; final String publishedAt; final String revision;
    final int fileCount; final long totalSizeBytes;
    final String[] labels; final String[][] notes;
    DataChangelog(String heading, String versionLine, String verifiedLine, String dataVersion, String publishedAt,
                  String revision, int fileCount, long totalSizeBytes, String[] labels, String[][] notes) {
      this.heading = heading; this.versionLine = versionLine; this.verifiedLine = verifiedLine;
      this.dataVersion = dataVersion; this.publishedAt = publishedAt; this.revision = revision;
      this.fileCount = fileCount; this.totalSizeBytes = totalSizeBytes; this.labels = labels; this.notes = notes;
    }
    boolean isEmpty() {
      for (String[] group : notes) if (group.length > 0) return false;
      return true;
    }
  }

  /**
   * The data changelog of the pending content, localized for the device, or null when
   * this descriptor carries none. Every claim is cross-checked against the catalog
   * itself: a block that does not describe exactly the verified bytes is dropped.
   */
  static DataChangelog dataChangelogFor(JSONObject update, Locale locale) {
    try {
      JSONObject catalog = catalogFor(update);
      Object raw = catalog == null ? null : catalog.opt("changelog");
      if (!(raw instanceof JSONObject)) return null;
      JSONObject block = (JSONObject) raw;
      if (block.toString().length() > MAX_CONTENT_CHANGELOG_JSON_BYTES) return null;
      if (!"content".equals(requireJsonString(block, "kind"))) return null;
      String dataVersion = requireJsonString(block, "dataVersion").trim();
      if (!dataVersion.matches("\\d{4}\\.\\d{2}\\.\\d{2}(\\.\\d{1,3})?")) return null;
      String publishedAt = requireJsonString(block, "publishedAt").trim();
      if (!publishedAt.matches("\\d{4}-\\d{2}-\\d{2}")) return null;
      String revision = requireJsonString(block, "revision").trim();
      if (!revision.matches("[0-9a-f]{8,64}") || !revision.equals(requireJsonString(catalog, "revision"))) return null;
      int fileCount = (int) requirePositiveLong(block, "fileCount");
      long totalSizeBytes = requirePositiveLong(block, "totalSizeBytes");
      if (fileCount != catalog.getJSONArray("files").length()) return null;
      if (totalSizeBytes != requirePositiveLong(catalog, "totalSizeBytes")) return null;
      JSONArray categories = block.getJSONArray("categories");
      if (categories.length() == 0 || categories.length() > MAX_CHANGELOG_CATEGORIES) return null;
      String[] names = new String[categories.length()];
      for (int index = 0; index < names.length; index++) {
        Object value = categories.get(index);
        if (!(value instanceof String) || ((String) value).isEmpty()) return null;
        names[index] = (String) value;
      }
      JSONObject notices = block.getJSONObject("notices");
      if (notices.length() == 0 || notices.length() > MAX_CHANGELOG_TABLES) return null;
      JSONObject notice = null;
      for (String key : changelogLanguageKeys(locale)) {
        Object candidate = notices.opt(key);
        if (candidate instanceof JSONObject) { notice = (JSONObject) candidate; break; }
      }
      if (notice == null) return null;
      String heading = requireBoundedText(notice, "heading", MAX_CHANGELOG_LABEL_CHARS);
      String versionLine = requireBoundedText(notice, "versionLine", MAX_CHANGELOG_LABEL_CHARS);
      String verifiedLine = requireBoundedText(notice, "verifiedLine", MAX_CHANGELOG_LABEL_CHARS);
      JSONObject labels = notice.getJSONObject("labels");
      JSONObject notes = notice.getJSONObject("notes");
      String[] labelValues = new String[names.length];
      String[][] noteValues = new String[names.length][];
      int total = 0;
      for (int index = 0; index < names.length; index++) {
        String category = names[index];
        labelValues[index] = requireBoundedText(labels, category, MAX_CHANGELOG_LABEL_CHARS);
        JSONArray values = notes.getJSONArray(category);
        if (values.length() == 0 || values.length() > MAX_CHANGELOG_ENTRIES) return null;
        String[] entries = new String[values.length()];
        for (int entry = 0; entry < entries.length; entry++) {
          Object value = values.get(entry);
          if (!(value instanceof String)) return null;
          String text = ((String) value).trim();
          if (text.isEmpty() || text.length() > MAX_CHANGELOG_ENTRY_CHARS) return null;
          entries[entry] = text;
        }
        noteValues[index] = entries;
        total += entries.length;
      }
      if (total == 0) return null;
      return new DataChangelog(heading, versionLine, verifiedLine, dataVersion, publishedAt, revision,
                               fileCount, totalSizeBytes, labelValues, noteValues);
    } catch (Exception invalid) { return null; }
  }

  static String catalogRevision(JSONObject update) {
    JSONObject catalog = validCatalog(update);
    if (catalog == null) return null;
    try { return requireJsonString(catalog, "revision"); } catch (Exception invalid) { return null; }
  }

  /** True while the signed content revision differs from the acknowledged one. */
  static boolean catalogUpdateAvailable(Context context, JSONObject update) {
    if (context == null) return false;
    String revision = catalogRevision(update);
    if (revision == null) return false;
    String seen = context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE).getString(SEEN_CATALOG_REVISION, null);
    return !revision.equals(seen);
  }

  static boolean isRequiredCatalog(JSONObject update) {
    try {
      JSONObject catalog = validCatalog(update);
      if (catalog == null) return false;
      if (!"required".equals(requireJsonString(catalog, "mode"))) return false;
      Long expiry = optionalUtcExpiration(catalog, "expiresAt");
      return expiry == null || System.currentTimeMillis() < expiry;
    } catch (Exception invalid) { return false; }
  }

  /** Folder that holds one app, e.g. /archive/projects/apks/<slug>/update.json -> /archive/projects/apks/ */
  private static String archiveRootPath(URL endpoint) {
    String path = endpoint.getPath();
    int lastSlash = path.lastIndexOf('/');
    int previous = lastSlash > 0 ? path.lastIndexOf('/', lastSlash - 1) : -1;
    return previous <= 0 ? path : path.substring(0, previous + 1);
  }

  /**
   * Strict validation of the optional content block. Every file URL must live on
   * the archive origin inside this app's own folder, carry a SHA-256 and match
   * the advertised total, so a signed descriptor can never point the client at
   * another app's bytes or an unverifiable payload.
   */
  static JSONObject validCatalog(JSONObject update) {
    if (update == null || !update.has("catalog") || update.isNull("catalog")) return null;
    try {
      JSONObject catalog = requireJsonObject(update, "catalog");
      String revision = requireJsonString(catalog, "revision");
      if (!revision.matches("[0-9a-f]{8,64}")) return null;
      String mode = requireJsonString(catalog, "mode");
      if (!("optional".equals(mode) || "recommended".equals(mode) || "required".equals(mode))) return null;
      long total = requirePositiveLong(catalog, "totalSizeBytes");
      if (total <= 0L || total > MAX_CATALOG_TOTAL_BYTES) return null;
      JSONArray files = catalog.optJSONArray("files");
      if (files == null || files.length() == 0 || files.length() > MAX_CATALOG_FILES) return null;
      URL endpoint = endpointUrl();
      String root = archiveRootPath(endpoint);
      String appPath = endpoint.getPath().substring(root.length(), endpoint.getPath().lastIndexOf('/'));
      if (requirePositiveLong(catalog, "fileCount") != files.length()) return null;
      java.util.HashSet<String> names = new java.util.HashSet<>();
      long summed = 0L;
      for (int index = 0; index < files.length(); index++) {
        JSONObject file = files.optJSONObject(index);
        if (file == null) return null;
        long size = requirePositiveLong(file, "sizeBytes");
        if (size <= 0L || size > MAX_APK_BYTES) return null;
        if (!requireJsonString(file, "sha256").matches("[0-9a-fA-F]{64}")) return null;
        if (requireJsonString(file, "label").length() == 0) return null;
        String name = requireJsonString(file, "file");
        if (name.length() == 0 || name.contains("..") || name.indexOf('/') >= 0 || name.indexOf((char) 92) >= 0 || !names.add(name)) return null;
        URL fileUrl = new URL(requireJsonString(file, "url"));
        if (!sameArchiveOrigin(endpoint, fileUrl)) return null;
        String filePath = fileUrl.getPath();
        if (!filePath.startsWith(root + "data/" + appPath + "/") && !filePath.startsWith(root + appPath + "/")) return null;
        if (!filePath.endsWith("/" + name)) return null;
        summed += size;
      }
      if (summed != total) return null;
      return catalog;
    } catch (Exception invalid) { return null; }
  }

  static boolean catalogContentVerified(Context context, JSONObject update) {
    try {
      JSONObject catalog = validCatalog(update);
      if (catalog == null) return false;
      File directory = contentDirectoryFor(context, catalog);
      JSONArray files = catalog.getJSONArray("files");
      for (int index = 0; index < files.length(); index++) {
        JSONObject file = files.getJSONObject(index);
        File target = new File(directory, requireJsonString(file, "file"));
        if (!target.isFile() || target.length() != requirePositiveLong(file, "sizeBytes")) return false;
        if (!matchesSha256(target, requireJsonString(file, "sha256"))) return false;
      }
      return true;
    } catch (Exception invalid) { return false; }
  }

  /** App-private home of the verified content for the revision in this descriptor. */
  public static File contentDirectory(Context context, JSONObject update) {
    try {
      JSONObject catalog = validCatalog(update);
      if (catalog == null || context == null) return null;
      return contentDirectoryFor(context, catalog);
    } catch (Exception invalid) { return null; }
  }

  private static File contentDirectoryFor(Context context, JSONObject catalog) throws Exception {
    File root = new File(context.getFilesDir(), CONTENT_DIRECTORY);
    return new File(root, requireJsonString(catalog, "revision"));
  }

  /**
   * Records that this install is aware of the current content revision, and tells
   * the host app that verified bytes are on disk. The app stays in charge of what
   * it does with the content; the notice never claims it imported anything.
   */
  public static void acknowledgeCatalog(Context context, JSONObject update) {
    if (context == null) return;
    try {
      String revision = catalogRevision(update);
      if (revision == null) return;
      context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE).edit().putString(SEEN_CATALOG_REVISION, revision).apply();
      // Postponement acknowledges a revision but must never publish content-ready.
      File completed = new File(contentDirectory(context, update), "verified-catalog.json");
      if (!completed.isFile()) return;
      Intent ready = new Intent(context.getPackageName() + CONTENT_READY_ACTION).setPackage(context.getPackageName());
      ready.putExtra("revision", revision);
      File directory = contentDirectory(context, update);
      if (directory != null) ready.putExtra("directory", directory.getAbsolutePath());
      context.sendBroadcast(ready);
    } catch (Exception ignored) { }
  }

  static int catalogPostponementsUsed(Context context, String revision) {
    if (context == null || revision == null) return NOT_NOW_LIMIT;
    return context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE).getInt(CATALOG_NOT_NOW_PREFIX + revision, 0);
  }

  static boolean canPostponeCatalog(Context context, String revision) {
    return catalogPostponementsUsed(context, revision) < NOT_NOW_LIMIT;
  }

  static void recordCatalogPostponement(Context context, String revision) {
    if (context == null || revision == null) return;
    int used = catalogPostponementsUsed(context, revision);
    if (used >= NOT_NOW_LIMIT) return;
    context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE).edit().putInt(CATALOG_NOT_NOW_PREFIX + revision, used + 1).apply();
  }

  /** Result of a verified content transfer; the app decides how to consume it. */
  static final AtomicBoolean CATALOG_ACTIVE = new AtomicBoolean(false);
  private static WeakReference<CatalogResult> CATALOG_RESULT = new WeakReference<>(null);
  public interface CatalogResult {
    void onReady(File directory);
    void onUnavailable(boolean needsArchive);
  }

  public static void downloadCatalog(Activity activity, JSONObject update, DownloadProgress progress, CatalogResult result) {
    JSONObject catalog = catalogFor(update);
    if (activity == null || catalog == null || result == null) {
      if (result != null) result.onUnavailable(false);
      return;
    }
    CATALOG_RESULT = new WeakReference<>(result);
    ACTIVE_PROGRESS = new WeakReference<>(progress);
    if (!CATALOG_ACTIVE.compareAndSet(false, true)) { attachProgress(activity, progress); return; }
    if (!DOWNLOAD_ACTIVE.compareAndSet(false, true)) { CATALOG_ACTIVE.set(false); result.onUnavailable(false); return; }
    final String snapshot = update.toString();
    EXECUTOR.execute(() -> {
      boolean needsArchive = false;
      try {
        File directory = downloadVerifiedContent(activity, new JSONObject(snapshot), catalog, progress);
        if (directory == null) throw new java.io.IOException("content unavailable");
        acknowledgeCatalog(activity, new JSONObject(snapshot));
        CATALOG_ACTIVE.set(false); DOWNLOAD_ACTIVE.set(false);
        MAIN.post(() -> { CatalogResult current = CATALOG_RESULT.get(); if (current != null) current.onReady(directory); });
        return;
      } catch (java.io.IOException gated) {
        // A protected archive answers with a redirect to its gate page. That is not
        // a broken download, so the notice tells the user where to get the bytes.
        needsArchive = "content-gated".equals(gated.getMessage());
      } catch (Exception ignored) { }
      final boolean archiveRequired = needsArchive;
      CATALOG_ACTIVE.set(false); DOWNLOAD_ACTIVE.set(false);
      MAIN.post(() -> { CatalogResult current = CATALOG_RESULT.get(); if (current != null) current.onUnavailable(archiveRequired); });
    });
  }

  private static File downloadVerifiedContent(Activity activity, JSONObject update, JSONObject catalog, DownloadProgress progress) throws Exception {
    JSONArray files = catalog.getJSONArray("files");
    long total = requirePositiveLong(catalog, "totalSizeBytes");
    File directory = contentDirectoryFor(activity, catalog);
    if (!directory.isDirectory() && !directory.mkdirs()) throw new java.io.IOException("Cannot create private content directory");
    long done = 0L;
    reportProgress(activity, progress, 0L, total);
    URL endpoint = endpointUrl();
    for (int index = 0; index < files.length(); index++) {
      JSONObject file = files.getJSONObject(index);
      String name = requireJsonString(file, "file");
      long size = requirePositiveLong(file, "sizeBytes");
      String sha256 = requireJsonString(file, "sha256").toLowerCase(Locale.US);
      File target = new File(directory, name);
      if (matchesSha256(target, sha256) && target.length() == size) {
        done += size;
        reportProgress(activity, progress, done, total);
        continue;
      }
      URL source = new URL(requireJsonString(file, "url"));
      if (!sameArchiveOrigin(endpoint, source)) throw new java.io.IOException("Cross-origin content blocked");
      File temporary = File.createTempFile("content-", ".part", directory);
      try {
        HttpURLConnection connection = (HttpURLConnection) source.openConnection();
        connection.setConnectTimeout(10000); connection.setReadTimeout(60000); connection.setInstanceFollowRedirects(false);
        int status = connection.getResponseCode();
        if (status == 301 || status == 302 || status == 303 || status == 307 || status == 308) throw new java.io.IOException("content-gated");
        if (status == 401 || status == 403) throw new java.io.IOException("content-gated");
        if (status != 200) throw new java.io.IOException("content HTTP " + status);
        long declared = connection.getContentLengthLong();
        if (declared > MAX_APK_BYTES || (declared >= 0L && declared != size)) throw new java.io.IOException("Unexpected content length");
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        long reportedBytes = 0L;
        long reportedAt = System.currentTimeMillis();
        try (InputStream input = new BufferedInputStream(connection.getInputStream()); FileOutputStream output = new FileOutputStream(temporary)) {
          byte[] buffer = new byte[16384];
          long received = 0L;
          for (int count; (count = input.read(buffer)) != -1;) {
            received += count;
            if (received > size) throw new java.io.IOException("Content exceeds signed size");
            digest.update(buffer, 0, count);
            output.write(buffer, 0, count);
            long overall = done + received;
            if (progress != null && (received >= size || overall - reportedBytes >= PROGRESS_STEP_BYTES || System.currentTimeMillis() - reportedAt >= PROGRESS_INTERVAL_MS)) {
              reportedBytes = overall; reportedAt = System.currentTimeMillis();
              reportProgress(activity, progress, overall, total);
            }
          }
        } finally { connection.disconnect(); }
        if (!sha256.equals(hex(digest.digest())) || temporary.length() != size) throw new java.io.IOException("Content checksum or length mismatch");
        if (target.exists() && !target.delete()) throw new java.io.IOException("Cannot replace stale content");
        if (!temporary.renameTo(target)) throw new java.io.IOException("Cannot promote verified content");
      } finally { if (temporary.exists()) temporary.delete(); }
      done += size;
      reportProgress(activity, progress, done, total);
    }
    reportVerifying(activity, progress);
    // Publish the complete plan atomically, only after every signed byte passed.
    File marker = new File(directory, "verified-catalog.json");
    File stagedMarker = new File(directory, "verified-catalog.json.tmp");
    try (FileOutputStream output = new FileOutputStream(stagedMarker)) {
      output.write(catalog.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));
      output.getFD().sync();
    }
    if (!stagedMarker.renameTo(marker)) throw new java.io.IOException("Cannot activate verified content");
    return directory;
  }

  private static Long optionalUtcExpiration(JSONObject object, String key) throws Exception {
    if (!object.has(key) || object.isNull(key)) return null;
    String value = requireJsonString(object, key);
    Matcher match = UTC_RFC3339.matcher(value);
    if (!match.matches()) throw new java.io.IOException("Invalid UTC expiry");
    GregorianCalendar calendar = new GregorianCalendar(TimeZone.getTimeZone("UTC"), Locale.US);
    calendar.setLenient(false); calendar.clear();
    int millis = 0;
    if (match.group(7) != null) millis = Integer.parseInt((match.group(7) + "000").substring(0, 3));
    calendar.set(Integer.parseInt(match.group(1)), Integer.parseInt(match.group(2)) - 1, Integer.parseInt(match.group(3)), Integer.parseInt(match.group(4)), Integer.parseInt(match.group(5)), Integer.parseInt(match.group(6)));
    calendar.set(Calendar.MILLISECOND, millis);
    return calendar.getTimeInMillis();
  }

  private static File downloadVerifiedApk(Context context, JSONObject update, DownloadProgress progress) throws Exception {
    String sha256 = requireJsonString(update, "sha256").toLowerCase(Locale.US);
    long version = requirePositiveLong(update, "versionCode");
    long expectedSize = requirePositiveLong(update, "sizeBytes");
    File directory = new File(context.getFilesDir(), "dexcore-archive-updates");
    if (!directory.isDirectory() && !directory.mkdirs()) throw new java.io.IOException("Cannot create private update directory");
    File apk = new File(directory, "update-" + version + ".apk");
    if (matchesSha256(apk, sha256) && apk.length() == expectedSize && validateArchiveIdentity(context, apk, update)) { reportProgress(context, progress, expectedSize, expectedSize); return apk; }
    File temporary = File.createTempFile("update-", ".part", directory);
    try {
      URL endpoint = endpointUrl();
      URL download = new URL(requireJsonString(update, "downloadUrl"));
      if (!sameArchiveOrigin(endpoint, download)) throw new java.io.IOException("Cross-origin APK blocked");
      HttpURLConnection connection = (HttpURLConnection) download.openConnection();
      connection.setConnectTimeout(10000); connection.setReadTimeout(30000); connection.setInstanceFollowRedirects(false);
      if (connection.getResponseCode() != 200) throw new java.io.IOException("APK HTTP " + connection.getResponseCode());
      long declaredLength = connection.getContentLengthLong();
      if (declaredLength > MAX_APK_BYTES || (declaredLength >= 0L && declaredLength != expectedSize)) throw new java.io.IOException("Unexpected APK length");
      MessageDigest digest = MessageDigest.getInstance("SHA-256");
      reportProgress(context, progress, 0L, expectedSize);
      long reportedBytes = 0L;
      long reportedAt = System.currentTimeMillis();
      try (InputStream input = new BufferedInputStream(connection.getInputStream()); FileOutputStream output = new FileOutputStream(temporary)) {
        byte[] buffer = new byte[16384]; long total = 0L;
        for (int count; (count = input.read(buffer)) != -1;) {
          total += count;
          if (total > expectedSize || total > MAX_APK_BYTES) throw new java.io.IOException("APK exceeds signed size");
          digest.update(buffer, 0, count); output.write(buffer, 0, count);
          // The signed byte count drives the visible percentage, never the
          // server's header, so progress cannot exceed the verified artifact.
          if (progress != null && (total >= expectedSize || total - reportedBytes >= PROGRESS_STEP_BYTES || System.currentTimeMillis() - reportedAt >= PROGRESS_INTERVAL_MS)) {
            reportedBytes = total; reportedAt = System.currentTimeMillis();
            reportProgress(context, progress, total, expectedSize);
          }
        }
      } finally { connection.disconnect(); }
      reportVerifying(context, progress);
      if (!sha256.equals(hex(digest.digest())) || temporary.length() != expectedSize) throw new java.io.IOException("APK checksum or length mismatch");
      if (!validateArchiveIdentity(context, temporary, update)) throw new java.io.IOException("APK package, version, or signer mismatch");
      if (apk.exists() && !apk.delete()) throw new java.io.IOException("Cannot replace stale update");
      if (!temporary.renameTo(apk)) throw new java.io.IOException("Cannot promote verified update");
      return apk;
    } finally { if (temporary.exists()) temporary.delete(); }
  }

  private static boolean matchesSha256(File file, String expected) throws Exception {
    if (!file.isFile() || file.length() == 0L) return false;
    MessageDigest digest = MessageDigest.getInstance("SHA-256");
    try (InputStream input = new FileInputStream(file)) { byte[] buffer = new byte[16384]; for (int count; (count = input.read(buffer)) != -1;) digest.update(buffer, 0, count); }
    return expected.equals(hex(digest.digest()));
  }

  private static boolean requestAndroidInstall(Activity activity, File apk) {
    Uri uri = new Uri.Builder().scheme("content").authority(activity.getPackageName() + ".dexcore.archiveupdates").appendPath(apk.getName()).build();
    Intent installer = new Intent(Intent.ACTION_VIEW).setDataAndType(uri, "application/vnd.android.package-archive")
        .addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_ACTIVITY_NEW_TASK);
    // A transfer that finished while the app was in the background still has to
    // reach Android's installer, so a dead notice falls back to the app context.
    Context context = (activity.isFinishing() || activity.isDestroyed()) ? activity.getApplicationContext() : activity;
    try { context.startActivity(installer); return true; } catch (Exception ignored) { return false; }
  }

  private static long installedVersion(Context context) throws Exception {
    if (Build.VERSION.SDK_INT >= 28) return context.getPackageManager().getPackageInfo(context.getPackageName(), 0).getLongVersionCode();
    return context.getPackageManager().getPackageInfo(context.getPackageName(), 0).versionCode;
  }

  static boolean installedVersionAtLeast(Context context, long target) {
    try { return target >= 0L && installedVersion(context) >= target; } catch (Exception ignored) { return false; }
  }

  // "Not now" bookkeeping lives in the client so the compiled limit travels with
  // the installed baseline instead of the published release.
  static int postponementsUsed(Context context, long targetVersionCode) {
    if (context == null || targetVersionCode <= 0L) return NOT_NOW_LIMIT;
    return context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE).getInt(NOT_NOW_PREFIX + targetVersionCode, 0);
  }

  static boolean canPostpone(Context context, long targetVersionCode) {
    return postponementsUsed(context, targetVersionCode) < NOT_NOW_LIMIT;
  }

  static void recordPostponement(Context context, long targetVersionCode) {
    if (context == null || targetVersionCode <= 0L) return;
    int used = postponementsUsed(context, targetVersionCode);
    if (used >= NOT_NOW_LIMIT) return;
    context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE).edit().putInt(NOT_NOW_PREFIX + targetVersionCode, used + 1).apply();
  }

  private static JSONObject verifySignedDescriptor(String document) throws Exception {
    JSONObject envelope = new JSONObject(document);
    if (requireNonNegativeLong(envelope, "schema") != 3L || !"SHA256withECDSA".equals(requireJsonString(envelope, "signatureAlgorithm"))) throw new java.io.IOException("Unsupported descriptor signature");
    byte[] payload = Base64.decode(requireJsonString(envelope, "signedPayload"), Base64.DEFAULT);
    byte[] signatureBytes = Base64.decode(requireJsonString(envelope, "signature"), Base64.DEFAULT);
    Signature verifier = Signature.getInstance("SHA256withECDSA");
    verifier.initVerify(KeyFactory.getInstance("EC").generatePublic(new X509EncodedKeySpec(Base64.decode(PINNED_UPDATE_PUBLIC_KEY, Base64.DEFAULT))));
    verifier.update(payload);
    if (!verifier.verify(signatureBytes)) throw new java.io.IOException("Invalid descriptor signature");
    return new JSONObject(new String(payload, java.nio.charset.StandardCharsets.UTF_8));
  }

  private static boolean sameArchiveOrigin(URL expected, URL actual) {
    int expectedPort = expected.getPort() < 0 ? expected.getDefaultPort() : expected.getPort();
    int actualPort = actual.getPort() < 0 ? actual.getDefaultPort() : actual.getPort();
    return "https".equalsIgnoreCase(actual.getProtocol()) && expected.getProtocol().equalsIgnoreCase(actual.getProtocol())
        && expected.getHost().equalsIgnoreCase(actual.getHost()) && expectedPort == actualPort;
  }

  private static HashSet<String> currentSignerDigests(PackageInfo info) throws Exception {
    HashSet<String> values = new HashSet<>();
    if (Build.VERSION.SDK_INT >= 28) {
      if (info.signingInfo == null) return values;
      for (android.content.pm.Signature signature : info.signingInfo.getApkContentsSigners()) values.add(hex(MessageDigest.getInstance("SHA-256").digest(signature.toByteArray())));
    } else if (info.signatures != null) {
      for (android.content.pm.Signature signature : info.signatures) values.add(hex(MessageDigest.getInstance("SHA-256").digest(signature.toByteArray())));
    }
    return values;
  }

  private static HashSet<String> signingLineageDigests(PackageInfo info) throws Exception {
    HashSet<String> values = new HashSet<>();
    if (Build.VERSION.SDK_INT >= 28) {
      if (info.signingInfo == null) return values;
      android.content.pm.Signature[] signatures = info.signingInfo.hasMultipleSigners() ? info.signingInfo.getApkContentsSigners() : info.signingInfo.getSigningCertificateHistory();
      for (android.content.pm.Signature signature : signatures) values.add(hex(MessageDigest.getInstance("SHA-256").digest(signature.toByteArray())));
    } else if (info.signatures != null) {
      for (android.content.pm.Signature signature : info.signatures) values.add(hex(MessageDigest.getInstance("SHA-256").digest(signature.toByteArray())));
    }
    return values;
  }

  private static boolean hasMultipleSigners(PackageInfo info, HashSet<String> current) {
    if (Build.VERSION.SDK_INT >= 28) return info.signingInfo != null && info.signingInfo.hasMultipleSigners();
    return current.size() > 1;
  }

  static boolean signingIdentityCompatible(PackageInfo installed, PackageInfo archive) throws Exception {
    HashSet<String> installedCurrent = currentSignerDigests(installed);
    HashSet<String> archiveCurrent = currentSignerDigests(archive);
    if (installedCurrent.isEmpty() || archiveCurrent.isEmpty()) return false;
    boolean installedMultiple = hasMultipleSigners(installed, installedCurrent);
    boolean archiveMultiple = hasMultipleSigners(archive, archiveCurrent);
    if (installedMultiple || archiveMultiple) return installedMultiple && archiveMultiple && installedCurrent.equals(archiveCurrent);
    if (installedCurrent.size() != 1 || archiveCurrent.size() != 1) return false;
    HashSet<String> archiveHistory = signingLineageDigests(archive);
    return archiveHistory.containsAll(installedCurrent);
  }

  private static boolean validateArchiveIdentity(Context context, File apk, JSONObject update) throws Exception {
    PackageManager manager = context.getPackageManager();
    int flags = Build.VERSION.SDK_INT >= 28 ? PackageManager.GET_SIGNING_CERTIFICATES : PackageManager.GET_SIGNATURES;
    PackageInfo archive = manager.getPackageArchiveInfo(apk.getAbsolutePath(), flags);
    if (archive == null || !context.getPackageName().equals(archive.packageName) || !archive.packageName.equals(requireJsonString(update, "expectedPackageName"))) return false;
    long archiveVersion = Build.VERSION.SDK_INT >= 28 ? archive.getLongVersionCode() : archive.versionCode;
    if (archiveVersion != requirePositiveLong(update, "versionCode") || archiveVersion <= installedVersion(context)) return false;
    PackageInfo installed = manager.getPackageInfo(context.getPackageName(), flags);
    HashSet<String> archiveCurrent = currentSignerDigests(archive);
    if (!signingIdentityCompatible(installed, archive)) return false;
    JSONArray expected = requireJsonArray(update, "signingCertificateSha256");
    if (expected.length() == 0) return false;
    HashSet<String> signedDescriptorSigners = new HashSet<>();
    for (int i = 0; i < expected.length(); i++) {
      Object value = expected.get(i);
      if (!(value instanceof String) || !((String) value).matches("[0-9a-fA-F]{64}")) return false;
      signedDescriptorSigners.add(((String) value).toLowerCase(Locale.US));
    }
    return signedDescriptorSigners.size() == expected.length() && signedDescriptorSigners.equals(archiveCurrent);
  }

  private static boolean strictSignerArray(JSONObject update) throws Exception {
    JSONArray values = requireJsonArray(update, "signingCertificateSha256");
    if (values.length() == 0) return false;
    HashSet<String> unique = new HashSet<>();
    for (int index = 0; index < values.length(); index++) {
      Object value = values.get(index);
      if (!(value instanceof String) || !((String) value).matches("[0-9a-fA-F]{64}")) return false;
      unique.add(((String) value).toLowerCase(Locale.US));
    }
    return unique.size() == values.length();
  }

  private static String requireJsonString(JSONObject object, String key) throws Exception {
    Object value = object.get(key);
    if (!(value instanceof String)) throw new java.io.IOException(key + " must be a string");
    return (String) value;
  }
  private static JSONObject requireJsonObject(JSONObject object, String key) throws Exception {
    Object value = object.get(key);
    if (!(value instanceof JSONObject)) throw new java.io.IOException(key + " must be an object");
    return (JSONObject) value;
  }
  private static JSONArray requireJsonArray(JSONObject object, String key) throws Exception {
    Object value = object.get(key);
    if (!(value instanceof JSONArray)) throw new java.io.IOException(key + " must be an array");
    return (JSONArray) value;
  }
  private static long requireNonNegativeLong(JSONObject object, String key) throws Exception {
    Object value = object.get(key);
    if (!(value instanceof Integer) && !(value instanceof Long)) throw new java.io.IOException(key + " must be an integral 64-bit number");
    long number = ((Number) value).longValue();
    if (number < 0L) throw new java.io.IOException(key + " must be nonnegative");
    return number;
  }
  private static long requirePositiveLong(JSONObject object, String key) throws Exception {
    long value = requireNonNegativeLong(object, key);
    if (value == 0L) throw new java.io.IOException(key + " must be positive");
    return value;
  }
  private static Long optionalNonNegativeLong(JSONObject object, String key) throws Exception {
    return !object.has(key) || object.isNull(key) ? null : requireNonNegativeLong(object, key);
  }

  private static void notifyDownloadFailure(Activity activity, String message) {
    if (activity == null) return;
    activity.runOnUiThread(() -> { if (activity instanceof DceArchiveUpdateActivity) ((DceArchiveUpdateActivity) activity).showFailure(message); });
  }
  // Progress reaches a visible Activity through its main thread; a background or
  // auto-download context has no listener and stays silent.
  private static void reportProgress(Context context, DownloadProgress progress, long downloaded, long totalBytes) {
    PROGRESS_DOWNLOADED = downloaded;
    PROGRESS_TOTAL = totalBytes;
    DownloadProgress listener = ACTIVE_PROGRESS.get();
    if (listener == null) listener = progress;
    if (listener == null) return;
    if (context instanceof Activity) {
      final Activity activity = (Activity) context;
      final DownloadProgress target = listener;
      MAIN.post(() -> target.onBytes(downloaded, totalBytes));
    } else listener.onBytes(downloaded, totalBytes);
  }
  private static void reportVerifying(Context context, DownloadProgress progress) {
    DownloadProgress listener = ACTIVE_PROGRESS.get();
    if (listener == null) listener = progress;
    if (listener == null) return;
    if (context instanceof Activity) {
      final Activity activity = (Activity) context;
      final DownloadProgress target = listener;
      MAIN.post(target::onVerifying);
    } else listener.onVerifying();
  }
  /** A notice attaches at any time; a transfer already in flight reports at once. */
  public static void attachProgress(Activity activity, DownloadProgress progress) {
    if (progress == null) return;
    ACTIVE_PROGRESS = new WeakReference<>(progress);
    if (activity == null) return;
    if (!DOWNLOAD_ACTIVE.get()) return;
    final long downloaded = PROGRESS_DOWNLOADED;
    final long total = PROGRESS_TOTAL;
    activity.runOnUiThread(() -> { if (!activity.isFinishing()) progress.onBytes(downloaded, total); });
  }
  private static void notifyInstallerStarted(Activity activity) {
    if (activity instanceof DceArchiveUpdateActivity) ((DceArchiveUpdateActivity) activity).installerStarted();
  }

  private static void openUpdateActivity(Activity host, JSONObject update, boolean autoDownload) {
    Intent intent = new Intent(host, DceArchiveUpdateActivity.class);
    intent.putExtra(DceArchiveUpdateActivity.EXTRA_UPDATE, update.toString());
    intent.putExtra(DceArchiveUpdateActivity.EXTRA_AUTO_START, autoDownload);
    host.startActivity(intent);
  }
  /** Update lane of this installation. A debuggable build is a lab build. */
  private static String updateLane(Context context) {
    try {
      android.content.pm.ApplicationInfo info = context.getApplicationInfo();
      return (info.flags & android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE) != 0 ? "debug" : "release";
    } catch (Exception invalid) { return "release"; }
  }
  /**
   * Lane descriptor beside the configured endpoint: <app>/update.json becomes
   * <app>/<lane>/update.json, so debug and release installs update independently.
   * An internal endpoint already carries its edition-and-lane path and is used as is.
   */
  private static URL laneEndpointUrl(Context context) throws Exception {
    URL endpoint = endpointUrl();
    String path = endpoint.getPath();
    if (path.contains("/updates/")) return endpoint;
    return new URL(endpoint.toString().replace("/update.json", "/" + updateLane(context) + "/update.json"));
  }
  /** Directory the lane descriptor must point its downloads into. */
  private static String laneDirectoryPath(Context context) throws Exception {
    String path = laneEndpointUrl(context).getPath();
    return path.substring(0, path.lastIndexOf('/') + 1);
  }
  private static URL endpointUrl() throws Exception { return new URL(concealed(ENDPOINT_DATA, ENDPOINT_SEED)); }
  private static String concealed(int[] data, int seed) {
    byte[] clear = new byte[data.length]; int state = seed;
    for (int i = 0; i < data.length; i++) { state = state * 1664525 + 1013904223; clear[i] = (byte) (data[i] ^ (state & 0xff)); }
    return new String(clear, java.nio.charset.StandardCharsets.UTF_8);
  }
  private static String readUrl(String value) throws Exception { URL endpoint = endpointUrl(); URL requested = new URL(value); if (!sameArchiveOrigin(endpoint, requested)) throw new java.io.IOException("Cross-origin descriptor blocked"); HttpURLConnection c = (HttpURLConnection) requested.openConnection(); c.setConnectTimeout(5000); c.setReadTimeout(7000); c.setInstanceFollowRedirects(false); c.setRequestProperty("Accept", "application/json"); if (c.getResponseCode() != 200) throw new java.io.IOException("HTTP " + c.getResponseCode()); long length = c.getContentLengthLong(); if (length > MAX_DESCRIPTOR_BYTES) throw new java.io.IOException("Descriptor too large"); try (BufferedInputStream in = new BufferedInputStream(c.getInputStream()); ByteArrayOutputStream out = new ByteArrayOutputStream()) { byte[] b = new byte[4096]; int total = 0; for (int n; (n = in.read(b)) != -1;) { total += n; if (total > MAX_DESCRIPTOR_BYTES) throw new java.io.IOException("Descriptor too large"); out.write(b, 0, n); } return out.toString("UTF-8"); } finally { c.disconnect(); } }
  private static String hex(byte[] bytes) { StringBuilder out = new StringBuilder(); for (byte b : bytes) out.append(String.format(Locale.US, "%02x", b)); return out.toString(); }
}
