package com.dcenhance.xtream_player.dexcoreupdate;

import android.app.Activity;
import android.app.Dialog;
import android.annotation.SuppressLint;
import android.annotation.TargetApi;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.ColorDrawable;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.util.TypedValue;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.view.WindowManager;
import android.view.animation.DecelerateInterpolator;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.dcenhance.xtream_player.R;
import java.util.Locale;
import org.json.JSONObject;

/** Generated by DEXCORE: a framework-neutral update notice Activity. */
public final class DceArchiveUpdateActivity extends Activity implements DceArchiveUpdates.DownloadProgress {
  public static final String EXTRA_UPDATE = "dce_archive_update";
  public static final String EXTRA_AUTO_START = "dce_archive_update_auto_start";
  private static final String STATE_INSTALLER_PENDING = "dce_installer_pending";
  // Static analysis supplies only the fallbacks; the active host theme wins.
  private static final int DETECTED_PRIMARY = Color.parseColor("#ffb26b");
  private static final int DETECTED_BACKGROUND = Color.parseColor("#0a0a0b");
  private static final int DETECTED_TEXT = Color.parseColor("#f7f7f7");
  private static final int DETECTED_MUTED = Color.parseColor("#808081");
  // A host theme that declares no background of its own inherits one of these
  // framework defaults. They are named for the platform, not for the app, so the
  // palette detected in the app's own sources outranks them.
  private static final int[] BASELINE_BACKGROUNDS = {0xFF303030, 0xFFFAFAFA, 0xFFF5F5F5, 0xFFEEEEEE, 0xFFFFFFFF};
  private static final int ERROR_TONE = 0xFFFF8A80;
  private JSONObject update;
  private boolean required;
  private long targetVersion;
  private boolean installerPending;
  private Dialog dialog;
  private TextView status;
  private TextView progressText;
  private ProgressBar progressBar;
  private TextView updateNow;
  private TextView automatic;
  private TextView backgroundLoad;
  // The brand colour fills the primary action; accentInk is the same hue walked
  // toward the readable end so labels and strokes stay legible on the host card.
  private int accent;
  private int accentInk;
  // The card and its text, derived from the host's own background.
  private int surface;
  private int textPrimary;
  private int textMuted;
  private String[] copy;
  // A signed descriptor can announce an APK release, additional content, or both.
  // The notice presents only what is actually pending.
  private JSONObject catalog;
  private String catalogRevision;
  private boolean appUpdate;
  private boolean dataUpdate;
  private boolean catalogRequired;
  // The per-version changelog comes from the signed descriptor, already localized in
  // the 20 app languages by the archive.
  private DceArchiveUpdates.Changelog releaseNotes;
  private DceArchiveUpdates.DataChangelog dataNotes;
  private android.widget.ScrollView notesScroll;
  private LinearLayout notesBody;
  private boolean transferBusy;
  private boolean installAfterContent;
  private DceArchiveUpdates.CatalogResult contentResult;
  private TextView contentAction;

  @Override public void onCreate(Bundle state) {
    super.onCreate(state);
    resolveHostPalette();
    if (Build.VERSION.SDK_INT >= 33) Api33.registerBackCallback(this);
    try {
      update = new JSONObject(getIntent().getStringExtra(EXTRA_UPDATE));
      Object versionValue = update.get("versionName");
      Object targetValue = update.get("versionCode");
      if (!(versionValue instanceof String) || (!(targetValue instanceof Integer) && !(targetValue instanceof Long))) throw new IllegalArgumentException("Invalid update");
      targetVersion = ((Number) targetValue).longValue();
      if (targetVersion <= 0L) throw new IllegalArgumentException("Invalid update target");
      catalog = DceArchiveUpdates.catalogFor(update);
      catalogRevision = DceArchiveUpdates.catalogRevision(update);
      releaseNotes = DceArchiveUpdates.changelogFor(update, deviceLocale());
      dataNotes = DceArchiveUpdates.dataChangelogFor(update, deviceLocale());
      appUpdate = !DceArchiveUpdates.installedVersionAtLeast(this, targetVersion);
      dataUpdate = catalog != null && DceArchiveUpdates.catalogUpdateAvailable(this, update);
      catalogRequired = dataUpdate && DceArchiveUpdates.isRequiredCatalog(update);
      required = DceArchiveUpdates.isRequiredUpdate(this, update) || catalogRequired;
      installerPending = state != null && state.getBoolean(STATE_INSTALLER_PENDING, false);
      if (!appUpdate && !dataUpdate) { finish(); return; }
      showUpdate((String) versionValue);
    } catch (Exception invalid) { finish(); }
  }

  @Override protected void onResume() {
    super.onResume();
    if (!required) return;
    if (appUpdate && DceArchiveUpdates.installedVersionAtLeast(this, targetVersion)) {
      required = catalogRequired;
      if (!required) { if (dialog != null) dialog.dismiss(); finish(); }
    } else if (appUpdate && installerPending) {
      installerPending = false;
      showInstallationIncomplete();
    }
  }

  @Override protected void onSaveInstanceState(Bundle state) {
    state.putBoolean(STATE_INSTALLER_PENDING, installerPending);
    super.onSaveInstanceState(state);
  }

  @SuppressLint("GestureBackNavigation")
  @Override public void onBackPressed() { handleBack(); }

  private void handleBack() {
    // Back is the only postponement route now that the notice offers no "not now":
    // a postponement is consumed while the budget lasts, and afterwards every
    // dismissal route stays closed.
    postpone();
  }

  // Returns true only when the postponement was recorded and the notice closed.
  private boolean postpone() {
    if (transferBusy) return false;
    if (appUpdate) {
      if (!DceArchiveUpdates.canPostpone(this, targetVersion)) return false;
      DceArchiveUpdates.recordPostponement(this, targetVersion);
    } else if (catalogRequired || !dataUpdate) {
      return false;
    }
    // A postponed notice also settles any optional content it was announcing, so
    // the same revision does not come back with every foreground check.
    if (dataUpdate && !catalogRequired) DceArchiveUpdates.acknowledgeCatalog(this, update);
    if (dialog != null && dialog.isShowing()) dialog.dismiss();
    else finish();
    return true;
  }

  @TargetApi(33)
  private static final class Api33 {
    static void registerBackCallback(DceArchiveUpdateActivity activity) {
      activity.getOnBackInvokedDispatcher().registerOnBackInvokedCallback(
          android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT, activity::handleBack);
    }
  }

  void installerStarted() { if (isFinishing()) return; installerPending = true; showStatus(copy[6]); if (!required && dialog != null) { dialog.dismiss(); finish(); } }
  void showFailure(String ignored) {
    installerPending = false;
    transferBusy = false;
    if (backgroundLoad != null) backgroundLoad.setEnabled(true);
    hideProgressSection();
    if (status != null) { status.setText(copy[7]); status.setTextColor(readableOn(ERROR_TONE, surface, 4.5d)); status.setVisibility(View.VISIBLE); }
    if (updateNow != null) { updateNow.setEnabled(true); updateNow.setAlpha(1f); updateNow.setText(copy[9]); }
    if (automatic != null) { automatic.setEnabled(true); automatic.setAlpha(1f); }
  }
  private void showInstallationIncomplete() {
    installerPending = false;
    transferBusy = false;
    if (backgroundLoad != null) backgroundLoad.setEnabled(true);
    hideProgressSection();
    if (status != null) { status.setText(copy[8]); status.setTextColor(readableOn(ERROR_TONE, surface, 4.5d)); status.setVisibility(View.VISIBLE); }
    if (updateNow != null) { updateNow.setEnabled(true); updateNow.setAlpha(1f); updateNow.setText(copy[9]); }
    if (automatic != null) { automatic.setEnabled(true); automatic.setAlpha(1f); }
  }
  private void showStatus(String message) { if (status != null) { status.setText(message); status.setTextColor(textMuted); status.setVisibility(View.VISIBLE); } }
  private void showProgressSection() {
    if (progressBar != null) { progressBar.setIndeterminate(false); progressBar.setVisibility(View.VISIBLE); progressBar.setProgress(0); }
    if (progressText != null) { progressText.setVisibility(View.VISIBLE); }
  }
  private void hideProgressSection() {
    if (progressBar != null) progressBar.setVisibility(View.GONE);
    if (progressText != null) progressText.setVisibility(View.GONE);
  }
  // Byte progress comes from the signed archive size, so the percentage and the
  // megabyte counters always describe the exact artifact being installed.
  @Override public void onBytes(long downloaded, long totalBytes) {
    if (progressBar == null || progressText == null || totalBytes <= 0L) return;
    long clamped = downloaded < 0L ? 0L : (downloaded > totalBytes ? totalBytes : downloaded);
    int percent = (int) (clamped * 100L / totalBytes);
    progressBar.setIndeterminate(false);
    progressBar.setVisibility(View.VISIBLE);
    if (Build.VERSION.SDK_INT >= 24) progressBar.setProgress(percent * 10, true);
    else progressBar.setProgress(percent * 10);
    progressText.setVisibility(View.VISIBLE);
    progressText.setText(String.format(deviceLocale(), copy[11], percent, megabytes(clamped), megabytes(totalBytes)));
    progressBar.setContentDescription(progressText.getText());
    // The byte line replaces the generic phase text instead of stacking on it.
    if (status != null) status.setVisibility(View.GONE);
  }
  @Override public void onVerifying() {
    if (progressText == null) return;
    if (progressBar != null) { progressBar.setIndeterminate(false); progressBar.setProgress(1000); progressBar.setVisibility(View.VISIBLE); }
    progressText.setVisibility(View.VISIBLE);
    progressText.setText(copy[12]);
    if (status != null) status.setVisibility(View.GONE);
  }
  private static String megabytes(long bytes) { return String.format(Locale.US, "%.1f", bytes / 1048576d); }
  // The size change the user sees is measured, not estimated: the signed release size
  // against the APK this device is actually running.
  private long installedApkBytes() {
    try {
      android.content.pm.ApplicationInfo info = getApplicationInfo();
      String path = info == null ? null : info.sourceDir;
      long length = path == null ? 0L : new java.io.File(path).length();
      return length > 0L ? length : 0L;
    } catch (Exception unavailable) { return 0L; }
  }
  private String sizeChangeText() {
    if (releaseNotes == null) return null;
    long installed = installedApkBytes();
    long target = 0L;
    try { target = update.getLong("sizeBytes"); } catch (Exception invalid) { target = 0L; }
    if (installed <= 0L || target <= 0L) return null;
    long delta = target - installed;
    String change;
    if (delta == 0L) change = releaseNotes.same;
    else change = String.format(deviceLocale(), delta > 0L ? releaseNotes.larger : releaseNotes.smaller, megabytes(Math.abs(delta)));
    return String.format(deviceLocale(), releaseNotes.sizeLine, megabytes(installed), megabytes(target)) + " · " + change;
  }
  // The notes area is built from the same primitives for a release and for a data
  // update, so both read the same way in every language.
  private TextView notesHeading(String value, int topMargin) {
    TextView view = text(value, 12, textMuted, true); view.setLetterSpacing(.10f);
    LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(-1, -2); params.topMargin = topMargin;
    view.setLayoutParams(params);
    return view;
  }
  private TextView notesLine(String value, int topMargin, int color) {
    TextView view = text(value, 12, color, false); view.setLineSpacing(dp(3), 1f);
    LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(-1, -2); params.topMargin = topMargin;
    view.setLayoutParams(params);
    return view;
  }
  private void notesCategories(LinearLayout body, String[] labels, String[][] notes) {
    for (int group = 0; group < labels.length; group++) {
      if (notes[group].length == 0) continue;
      TextView groupLabel = text(labels[group], 12, accentInk, true);
      LinearLayout.LayoutParams groupLabelLp = new LinearLayout.LayoutParams(-1, -2);
      groupLabelLp.topMargin = group == 0 ? dp(12) : dp(14);
      body.addView(groupLabel, groupLabelLp);
      for (String note : notes[group]) {
        TextView noteLine = text("• " + note, 13, textMuted, false); noteLine.setLineSpacing(dp(3), 1f);
        LinearLayout.LayoutParams noteLp = new LinearLayout.LayoutParams(-1, -2); noteLp.topMargin = dp(6);
        body.addView(noteLine, noteLp);
      }
    }
  }
  private void setNotesHeight(int height) {
    if (notesScroll == null) return;
    ViewGroup.LayoutParams params = notesScroll.getLayoutParams();
    if (params == null) return;
    params.height = height;
    notesScroll.setLayoutParams(params);
  }
  private int notesHeight() { return notesScroll == null || notesScroll.getLayoutParams() == null ? 0 : notesScroll.getLayoutParams().height; }
  // The user does not want to stand and watch: the verified transfer starts exactly
  // like the primary action and the screen steps aside, so the phone stays usable
  // while the bytes arrive. The activity keeps running; coming back shows the real
  // progress instead of a promise. Android may still require the user to return for
  // the installer step, which is exactly what the notice then asks for.
  private void loadInBackground() {
    if (transferBusy) return;
    startDownload();
    showStatus(copy[10]);
    moveTaskToBack(true);
  }

  private void startDownload() {
    if (transferBusy) return;
    if (dataUpdate) { installAfterContent = appUpdate; startCatalogDownload(); return; }
    if (appUpdate && Build.VERSION.SDK_INT >= 26 && !getPackageManager().canRequestPackageInstalls()) {
      showStatus("Allow installs for this app in Android Settings, then return and tap Continue. Android will ask you to approve installation.");
      updateNow.setText("Continue to install"); updateNow.setEnabled(true); updateNow.setAlpha(1f);
      try { startActivity(new Intent(android.provider.Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, Uri.parse("package:" + getPackageName()))); }
      catch (Exception unavailable) { showStatus("Open Android Settings → Special app access → Install unknown apps, allow this app, then try again."); }
      return;
    }
    transferBusy = true;
    if (backgroundLoad != null) backgroundLoad.setEnabled(false);
    showStatus(copy[10]);
    showProgressSection();
    updateNow.setEnabled(false); updateNow.setAlpha(.62f);
    automatic.setEnabled(false); automatic.setAlpha(.62f);
    if (contentAction != null) { contentAction.setEnabled(false); contentAction.setAlpha(.62f); }
    DceArchiveUpdates.downloadAndInstall(this, update, this);
  }

  // Verified content transfer: the bytes land in this app's private directory and
  // the host app is told through a broadcast. The notice never claims that the app
  // imported or applied the content on its own.
  private void startCatalogDownload() {
    if (transferBusy) return;
    transferBusy = true;
    if (backgroundLoad != null) backgroundLoad.setEnabled(false);
    showStatus(copy[10]);
    showProgressSection();
    if (updateNow != null) { updateNow.setEnabled(false); updateNow.setAlpha(.62f); }
    if (automatic != null) { automatic.setEnabled(false); automatic.setAlpha(.62f); }
    if (contentAction != null) { contentAction.setEnabled(false); contentAction.setAlpha(.62f); }
    contentResult = new DceArchiveUpdates.CatalogResult() {
      @Override public void onReady(java.io.File directory) {
        if (isFinishing()) return;
        transferBusy = false;
        dataUpdate = false;
        catalogRequired = false;
        if (installAfterContent) { installAfterContent = false; startDownload(); return; }
        hideProgressSection();
        showStatus("Content verified — ready to use offline.");
        updateNow.setEnabled(true); updateNow.setAlpha(1f);
        updateNow.setText(appUpdate ? copy[3] : copy[23]);
        updateNow.setOnClickListener(view -> { if (appUpdate) startDownload(); else finish(); });
        if (contentAction != null) contentAction.setVisibility(View.GONE);
        if (backgroundLoad != null) backgroundLoad.setEnabled(true);
      }
      @Override public void onUnavailable(boolean needsArchive) {
        transferBusy = false;
        if (backgroundLoad != null) backgroundLoad.setEnabled(true);
        if (isFinishing()) return;
        hideProgressSection();
        if (status != null) {
          status.setText(needsArchive ? copy[17] : copy[18]);
          status.setTextColor(readableOn(ERROR_TONE, surface, 4.5d));
          status.setVisibility(View.VISIBLE);
        }
        if (updateNow != null) {
          updateNow.setEnabled(true); updateNow.setAlpha(1f);
          updateNow.setText(needsArchive ? copy[19] : copy[9]);
          updateNow.setOnClickListener(view -> { if (needsArchive) openArchivePage(); else startCatalogDownload(); });
        }
        if (contentAction != null) { contentAction.setEnabled(true); contentAction.setAlpha(1f); }
        if (automatic != null) { automatic.setEnabled(true); automatic.setAlpha(1f); }
      }
    };
    DceArchiveUpdates.downloadCatalog(this, update, this, contentResult);
  }

  private void openArchivePage() {
    try {
      String page = DceArchiveUpdates.archivePageUrl();
      if (page != null) startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(page)));
    } catch (Exception ignored) { }
  }

  @SuppressWarnings("deprecation")
  private Locale deviceLocale() {
    if (Build.VERSION.SDK_INT >= 24) return getResources().getConfiguration().getLocales().get(0);
    return getResources().getConfiguration().locale;
  }

  // The notice is injected into an app it does not own, so its whole chrome comes
  // from the host: the brand colour, the background the app draws on, and the text
  // it draws. The live theme wins; the palette detected in the app's own sources is
  // the fallback, never a fixed dark card that belongs to no app.
  private void resolveHostPalette() {
    // The archive owner's pinned colour wins over detection: the signed descriptor is
    // the only lever that can correct a wrong colour without rebuilding the app.
    int pinned = DceArchiveUpdates.noticeAccent();
    accent = pinned != 0 ? pinned : resolveHostPrimaryColor();
    int background = resolveHostBackground();
    surface = noticeSurface(background, accent);
    textPrimary = readableText(hostThemeText(0), surface, DETECTED_TEXT, 4.5d);
    textMuted = readableText(hostThemeText(1), surface, DETECTED_MUTED, 3d);
    accentInk = readableOn(accent, surface, 3d);
  }

  // 0 = primary host text colour, 1 = secondary.
  private int hostThemeText(int index) {
    int attribute = index == 0 ? android.R.attr.textColorPrimary : android.R.attr.textColorSecondary;
    for (int themeResource : hostThemeResources()) {
      if (themeResource == 0) continue;
      android.content.res.Resources.Theme hostTheme = getResources().newTheme();
      try {
        hostTheme.applyStyle(themeResource, true);
      } catch (Exception ignored) { continue; }
      int color = resolveThemeColor(hostTheme, attribute);
      // A themed *text* colour decides how the whole notice reads. Hosts keep warning
      // and brand hues in the same attributes, and a hued one walks toward white on the
      // card - which is exactly how the notice text turned pink inside a red-branded
      // app. Only a near-neutral tone is accepted as text; a hued one falls through to
      // the app's own detected text colours.
      if (Color.alpha(color) >= 128 && isNeutralTone(color)) return color;
    }
    return index == 0 ? DETECTED_TEXT : DETECTED_MUTED;
  }

  private static boolean isNeutralTone(int color) {
    int high = Math.max(Color.red(color), Math.max(Color.green(color), Color.blue(color)));
    int low = Math.min(Color.red(color), Math.min(Color.green(color), Color.blue(color)));
    return high - low <= 40;
  }

  private int resolveHostBackground() {
    int frameworkDefault = 0;
    for (int themeResource : hostThemeResources()) {
      if (themeResource == 0) continue;
      android.content.res.Resources.Theme hostTheme = getResources().newTheme();
      try {
        hostTheme.applyStyle(themeResource, true);
      } catch (Exception ignored) { continue; }
      int background = resolveThemeColor(hostTheme, android.R.attr.windowBackground);
      if (Color.alpha(background) < 128) background = resolveThemeColor(hostTheme, android.R.attr.colorBackground);
      if (Color.alpha(background) < 128) continue;
      if (!isBaselineBackground(background)) return background;
      if (frameworkDefault == 0) frameworkDefault = background;
    }
    // The app's own palette beats a framework default its theme never replaced: a
    // Compose/Flutter host keeps its colours in code, so its theme still resolves
    // to the platform grey even though the app renders near-black or white.
    if (Color.alpha(DETECTED_BACKGROUND) >= 128) return DETECTED_BACKGROUND;
    return frameworkDefault != 0 ? frameworkDefault : DETECTED_BACKGROUND;
  }

  private static boolean isBaselineBackground(int color) {
    for (int baseline : BASELINE_BACKGROUNDS) if (color == baseline) return true;
    return false;
  }

  private int resolveHostPrimaryColor() {
    int declaredPrimary = getResources().getIdentifier("colorPrimary", "attr", getPackageName());
    for (int themeResource : hostThemeResources()) {
      if (themeResource == 0) continue;
      android.content.res.Resources.Theme hostTheme = getResources().newTheme();
      try {
        hostTheme.applyStyle(themeResource, true);
      } catch (Exception ignored) { continue; }
      // The framework attribute is the app's own declaration; the package-scoped
      // identifier only matters on hosts that redefine the attribute themselves.
      int primary = resolveThemeColor(hostTheme, android.R.attr.colorPrimary);
      if (!isUsableThemePrimary(hostTheme, primary)) primary = resolveThemeColor(hostTheme, declaredPrimary);
      if (isUsableThemePrimary(hostTheme, primary)) return primary;
    }
    // A host whose colours live in code (Compose, Flutter) exposes no themed primary,
    // so the primary detected in its own sources is authoritative, not a generic hue.
    if (Color.alpha(DETECTED_PRIMARY) >= 128) return DETECTED_PRIMARY;
    for (int themeResource : hostThemeResources()) {
      if (themeResource == 0) continue;
      android.content.res.Resources.Theme hostTheme = getResources().newTheme();
      try {
        hostTheme.applyStyle(themeResource, true);
      } catch (Exception ignored) { continue; }
      int accent = resolveThemeColor(hostTheme, android.R.attr.colorAccent);
      if (isUsableThemePrimary(hostTheme, accent)) return accent;
    }
    return DETECTED_PRIMARY;
  }

  /** The launcher activity theme first, then the application theme. */
  private int[] hostThemeResources() {
    int launcherTheme = 0;
    int applicationTheme = 0;
    try {
      Intent launcher = getPackageManager().getLaunchIntentForPackage(getPackageName());
      if (launcher != null && launcher.getComponent() != null) {
        launcherTheme = getPackageManager().getActivityInfo(launcher.getComponent(), 0).getThemeResource();
      }
    } catch (Exception ignored) { /* Falls back to the application theme. */ }
    try {
      applicationTheme = getApplicationInfo().theme;
    } catch (Exception ignored) { /* Falls back to the detected primary. */ }
    return new int[]{launcherTheme, applicationTheme};
  }

  @SuppressWarnings("deprecation")
  private int resolveThemeColor(android.content.res.Resources.Theme hostTheme, int attribute) {
    if (attribute == 0) return Color.TRANSPARENT;
    TypedValue value = new TypedValue();
    if (!hostTheme.resolveAttribute(attribute, value, true)) return Color.TRANSPARENT;
    if (value.type >= TypedValue.TYPE_FIRST_COLOR_INT && value.type <= TypedValue.TYPE_LAST_COLOR_INT) return value.data;
    if (value.resourceId != 0) {
      try { return getResources().getColor(value.resourceId); } catch (Exception ignored) { return Color.TRANSPARENT; }
    }
    return Color.TRANSPARENT;
  }

  private boolean isUsableThemePrimary(android.content.res.Resources.Theme hostTheme, int color) {
    if (Color.alpha(color) < 128) return false;
    // A theme that never declared a brand primary inherits one of these baseline
    // hues; treating them as the app's identity paints the notice in Material
    // purple for every host that keeps its colours in code.
    if (color == 0xFF6200EE || color == 0xFF3F51B5 || color == 0xFF6750A4 || color == 0xFF2196F3) return false;
    int background = resolveThemeColor(hostTheme, android.R.attr.windowBackground);
    if (Color.alpha(background) >= 128) {
      int red = Color.red(color) - Color.red(background);
      int green = Color.green(color) - Color.green(background);
      int blue = Color.blue(color) - Color.blue(background);
      if (red * red + green * green + blue * blue < 24 * 24) return false;
    }
    return true;
  }

  private static double channel(int value) {
    double srgb = value / 255d;
    return srgb <= .03928d ? srgb / 12.92d : Math.pow((srgb + .055d) / 1.055d, 2.4d);
  }

  private static double luminance(int color) {
    return .2126d * channel(Color.red(color)) + .7152d * channel(Color.green(color)) + .0722d * channel(Color.blue(color));
  }

  private static double contrast(int first, int second) {
    double a = luminance(first), b = luminance(second);
    return (Math.max(a, b) + .05d) / (Math.min(a, b) + .05d);
  }

  private static int blend(int from, int to, double amount) {
    return Color.rgb(
        (int) Math.round(Color.red(from) + (Color.red(to) - Color.red(from)) * amount),
        (int) Math.round(Color.green(from) + (Color.green(to) - Color.green(from)) * amount),
        (int) Math.round(Color.blue(from) + (Color.blue(to) - Color.blue(from)) * amount));
  }

  private static boolean isLight(int background) { return luminance(background) > .45d; }

  private static int textOn(int background) { return isLight(background) ? 0xFF14121A : 0xFFF4F2FA; }

  // Keep the host's own hue but walk it toward the readable end until the contrast
  // holds, so a pale brand colour is still legible on a light card and a deep one on
  // a dark card.
  private static int readableOn(int color, int background, double minimum) {
    if (Color.alpha(color) < 128) color = textOn(background);
    if (contrast(color, background) >= minimum) return color;
    int toward = isLight(background) ? Color.BLACK : Color.WHITE;
    for (int step = 1; step <= 12; step++) {
      int adjusted = blend(color, toward, step / 12d);
      if (contrast(adjusted, background) >= minimum) return adjusted;
    }
    return toward;
  }

  private static int readableText(int candidate, int background, int fallback, double minimum) {
    if (Color.alpha(candidate) >= 128 && contrast(candidate, background) >= minimum) return candidate;
    // The platform's own text colour and the host's detected one describe the same
    // role; the one that actually stands out on this card wins, so a light host is
    // never labelled with near-white text that has to be walked back down.
    int computed = textOn(background);
    int base = Color.alpha(fallback) >= 128 && contrast(fallback, background) > contrast(computed, background) ? fallback : computed;
    return readableOn(base, background, minimum);
  }

  // Material tints an elevated surface with the app's own primary; a fixed grey card
  // is exactly what made the notice read as a foreign dialog inside its host.
  private int noticeSurface(int background, int brand) {
    boolean light = isLight(background);
    int card = blend(background, brand, light ? .03d : .05d);
    if (!light) {
      card = blend(card, Color.WHITE, .03d);
      if (contrast(card, background) < 1.06d) card = blend(background, Color.WHITE, .09d);
    }
    return card;
  }

  private void showUpdate(String version) {
    Locale locale = deviceLocale();
    copy = localized(locale);
    dialog = new Dialog(this);
    dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
    // Every dismissal is an explicit, counted postponement: no outside tap and
    // no back gesture may bypass the per-update budget.
    dialog.setCancelable(false);
    dialog.setCanceledOnTouchOutside(false);
    LinearLayout shell = new LinearLayout(this); shell.setOrientation(LinearLayout.VERTICAL); shell.setLayoutDirection(getResources().getConfiguration().getLayoutDirection()); shell.setPadding(dp(24), dp(20), dp(24), dp(22)); shell.setBackground(card(surface, 28));
    View accentRail = new View(this); accentRail.setBackground(round(accent, 3)); LinearLayout.LayoutParams railLp = new LinearLayout.LayoutParams(dp(52), dp(5)); railLp.gravity = Gravity.START; shell.addView(accentRail, railLp);

    LinearLayout header = new LinearLayout(this); header.setGravity(Gravity.CENTER_VERTICAL); LinearLayout.LayoutParams headerLp = new LinearLayout.LayoutParams(-1, -2); headerLp.topMargin = dp(18); shell.addView(header, headerLp);
    TextView source = text(copy[5], 12, textMuted, true); source.setLetterSpacing(.10f); header.addView(source, new LinearLayout.LayoutParams(-1, -2));

    TextView title = text(appUpdate ? copy[0] : copy[13], 25, textPrimary, true); title.setMaxLines(2); LinearLayout.LayoutParams titleLp = new LinearLayout.LayoutParams(-1, -2); titleLp.topMargin = dp(12); shell.addView(title, titleLp);
    String bodyText = appUpdate ? String.format(locale, copy[1], version) : String.format(locale, copy[14], DceArchiveUpdates.catalogSummaryLabel(update), megabytes(DceArchiveUpdates.catalogTotalBytes(update)) + " MB");
    TextView body = text(bodyText, 15, textMuted, false); body.setLineSpacing(dp(4), 1f); body.setMaxLines(3); LinearLayout.LayoutParams bodyLp = new LinearLayout.LayoutParams(-1, -2); bodyLp.topMargin = dp(8); shell.addView(body, bodyLp);
    if (appUpdate) {
      TextView versionChip = text(version, 12, textPrimary, true); versionChip.setGravity(Gravity.CENTER); versionChip.setPadding(dp(12), 0, dp(12), 0); versionChip.setBackground(round(blend(surface, textPrimary, .10d), 12)); LinearLayout.LayoutParams chipLp = new LinearLayout.LayoutParams(-2, dp(32)); chipLp.topMargin = dp(18); shell.addView(versionChip, chipLp);
      // Whether the release is bigger or smaller than what the device runs right now
      // is a real answer, not an estimate: installed APK bytes against the signed size.
      String sizeChange = sizeChangeText();
      if (sizeChange != null) {
        TextView sizeLine = text(sizeChange, 12, textMuted, false);
        sizeLine.setMaxLines(2);
        LinearLayout.LayoutParams sizeLp = new LinearLayout.LayoutParams(-1, -2); sizeLp.topMargin = dp(8);
        shell.addView(sizeLine, sizeLp);
      }
    }
    // Both kinds at once: the release stays the headline and the pending content is
    // announced as its own compact block instead of a second dialog.
    if (appUpdate && dataUpdate) {
      TextView contentLabel = text(copy[13], 12, textMuted, true); contentLabel.setLetterSpacing(.10f); LinearLayout.LayoutParams contentLabelLp = new LinearLayout.LayoutParams(-1, -2); contentLabelLp.topMargin = dp(18); shell.addView(contentLabel, contentLabelLp);
      TextView contentText = text(String.format(locale, copy[14], DceArchiveUpdates.catalogSummaryLabel(update), megabytes(DceArchiveUpdates.catalogTotalBytes(update)) + " MB"), 13, textMuted, false); contentText.setLineSpacing(dp(3), 1f); contentText.setMaxLines(3); LinearLayout.LayoutParams contentTextLp = new LinearLayout.LayoutParams(-1, -2); contentTextLp.topMargin = dp(6); shell.addView(contentText, contentTextLp);
    }
    TextView journey = text(copy[appUpdate ? 20 : 21], 11, accentInk, true);
    LinearLayout.LayoutParams journeyLp = new LinearLayout.LayoutParams(-1, -2); journeyLp.topMargin = dp(14); shell.addView(journey, journeyLp);
    // The release notes are the only part that can be long, so they get their own
    // scroll area inside the notice. The notice itself never scrolls: the version,
    // the actions and the byte progress stay where they are while the notes move.
    boolean appNotes = appUpdate && releaseNotes != null && !releaseNotes.isEmpty();
    boolean contentNotes = dataUpdate && dataNotes != null && !dataNotes.isEmpty();
    if (appNotes || contentNotes) {
      notesBody = new LinearLayout(this); notesBody.setOrientation(LinearLayout.VERTICAL); notesBody.setLayoutDirection(getResources().getConfiguration().getLayoutDirection());
      if (appNotes) {
        notesBody.addView(notesHeading(releaseNotes.heading, 0));
        notesCategories(notesBody, releaseNotes.labels, releaseNotes.notes);
      }
      // A data release documents itself: its own version, its publication date and the
      // verified catalog identity, followed by the categorized data changelog.
      if (contentNotes) {
        notesBody.addView(notesHeading(dataNotes.heading, appNotes ? dp(20) : 0));
        notesBody.addView(notesLine(String.format(locale, dataNotes.versionLine, dataNotes.dataVersion, dataNotes.publishedAt), dp(8), accentInk));
        notesBody.addView(notesLine(String.format(locale, dataNotes.verifiedLine, String.valueOf(dataNotes.fileCount), megabytes(dataNotes.totalSizeBytes), dataNotes.revision.substring(0, 8)), dp(4), textMuted));
        notesCategories(notesBody, dataNotes.labels, dataNotes.notes);
      }
      notesScroll = new android.widget.ScrollView(this);
      notesScroll.setFillViewport(false); notesScroll.setVerticalScrollBarEnabled(true);
      notesScroll.setOverScrollMode(View.OVER_SCROLL_IF_CONTENT_SCROLLS);
      notesScroll.setBackground(round(blend(surface, textPrimary, .05d), 14));
      notesScroll.setPadding(dp(12), dp(10), dp(12), dp(10)); notesScroll.setClipToPadding(false);
      notesScroll.addView(notesBody, new android.widget.FrameLayout.LayoutParams(-1, -2));
      LinearLayout.LayoutParams notesScrollLp = new LinearLayout.LayoutParams(-1, dp(160)); notesScrollLp.topMargin = dp(10);
      shell.addView(notesScroll, notesScrollLp);
    }
    status = text("", 13, textMuted, false); status.setVisibility(View.GONE); LinearLayout.LayoutParams statusLp = new LinearLayout.LayoutParams(-1, -2); statusLp.topMargin = dp(14); shell.addView(status, statusLp);

    LinearLayout progressWrap = new LinearLayout(this); progressWrap.setOrientation(LinearLayout.VERTICAL); LinearLayout.LayoutParams progressLp = new LinearLayout.LayoutParams(-1, -2); progressLp.topMargin = dp(12); shell.addView(progressWrap, progressLp);
    progressText = text("", 13, textPrimary, true); progressText.setVisibility(View.GONE); progressWrap.addView(progressText, new LinearLayout.LayoutParams(-1, -2));
    progressBar = new ProgressBar(this, null, android.R.attr.progressBarStyleHorizontal);
    progressBar.setMax(1000); progressBar.setProgress(0); progressBar.setVisibility(View.GONE);
    progressBar.setProgressTintList(android.content.res.ColorStateList.valueOf(accent));
    progressBar.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(blend(surface, textPrimary, .14d)));
    LinearLayout.LayoutParams barLp = new LinearLayout.LayoutParams(-1, dp(6)); barLp.topMargin = dp(8); progressWrap.addView(progressBar, barLp);

    LinearLayout actions = new LinearLayout(this); actions.setOrientation(LinearLayout.VERTICAL); LinearLayout.LayoutParams actionsLp = new LinearLayout.LayoutParams(-1, -2); actionsLp.topMargin = dp(26); shell.addView(actions, actionsLp);
    // The primary action always matches what is pending: the release, or the
    // content when the installed build is already current.
    updateNow = primaryButton(appUpdate && dataUpdate ? copy[22] : appUpdate ? copy[3] : copy[15]); actions.addView(updateNow, new LinearLayout.LayoutParams(-1, dp(52)));
    if (appUpdate) {
      automatic = secondaryButton(copy[2]); LinearLayout.LayoutParams automaticLp = new LinearLayout.LayoutParams(-1, dp(48)); automaticLp.topMargin = dp(10); actions.addView(automatic, automaticLp);
      automatic.setOnClickListener(view -> { getSharedPreferences(DceArchiveUpdates.PREFERENCES, Context.MODE_PRIVATE).edit().putBoolean(DceArchiveUpdates.AUTO_DOWNLOAD_UPDATES, true).remove(DceArchiveUpdates.LEGACY_SUPPRESS_DIALOGS).apply(); startDownload(); });
    }
    if (appUpdate && dataUpdate) {
      contentAction = secondaryButton(copy[15]);
      LinearLayout.LayoutParams contentLp = new LinearLayout.LayoutParams(-1, dp(48)); contentLp.topMargin = dp(10); actions.addView(contentAction, contentLp);
      contentAction.setOnClickListener(view -> { installAfterContent = false; startCatalogDownload(); });
    }
    // No "not now" any more: a waiting user gets a real alternative instead of a
    // dismissal. Back still postpones silently, so nothing nags every check.
    backgroundLoad = secondaryButton(copy[4]);
    LinearLayout.LayoutParams backgroundLp = new LinearLayout.LayoutParams(-1, dp(48)); backgroundLp.topMargin = dp(8); actions.addView(backgroundLoad, backgroundLp);
    backgroundLoad.setOnClickListener(view -> loadInBackground());
    // The notice stays visible while the verified download runs so the byte
    // progress is watchable; it closes when Android's installer takes over.
    updateNow.setOnClickListener(view -> startDownload());
    dialog.setOnDismissListener(ignored -> finish());
    // The notice is not a scrolling page: its root is the card itself, and only the
    // release notes inside it scroll. The dialog is a little taller than before so a
    // full release note fits without pushing the actions off the card.
    dialog.setContentView(shell);
    dialog.show();
    Window window = dialog.getWindow();
    if (window != null) {
      window.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));
      window.setDimAmount(.72f);
      window.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);
      if (Build.VERSION.SDK_INT >= 31) { window.addFlags(WindowManager.LayoutParams.FLAG_BLUR_BEHIND); window.setBackgroundBlurRadius(dp(28)); }
      float heightFraction = .92f;
      int width = Math.min(dp(440), (int) (getResources().getDisplayMetrics().widthPixels * .89f));
      int maxHeight = (int) (getResources().getDisplayMetrics().heightPixels * heightFraction);
      shell.measure(View.MeasureSpec.makeMeasureSpec(width, View.MeasureSpec.EXACTLY), View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED));
      // Long notes shrink the notes area, never the actions: the notice always fits.
      if (notesScroll != null && notesBody != null) {
        int natural = notesBody.getMeasuredHeight() + notesScroll.getPaddingTop() + notesScroll.getPaddingBottom();
        int cap = Math.min(dp(280), Math.max(dp(104), (int) (getResources().getDisplayMetrics().heightPixels * .34f)));
        setNotesHeight(Math.min(natural, cap));
        shell.measure(View.MeasureSpec.makeMeasureSpec(width, View.MeasureSpec.EXACTLY), View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED));
        for (int step = 0; step < 24 && shell.getMeasuredHeight() > maxHeight && notesHeight() > dp(104); step++) {
          setNotesHeight(notesHeight() - dp(12));
          shell.measure(View.MeasureSpec.makeMeasureSpec(width, View.MeasureSpec.EXACTLY), View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED));
        }
      }
      window.setLayout(width, Math.min(shell.getMeasuredHeight(), maxHeight));
    }
    shell.setAlpha(0f); shell.setScaleX(.965f); shell.setScaleY(.965f); shell.setTranslationY(dp(18));
    shell.animate().alpha(1f).scaleX(1f).scaleY(1f).translationY(0f).setStartDelay(36).setDuration(240).setInterpolator(new DecelerateInterpolator(1.65f)).start();
    // Returning from the background re-opens the notice while the verified transfer
    // keeps running, so the live byte state is re-attached instead of restarted.
    DceArchiveUpdates.attachProgress(this, this);
    if (dataUpdate && DceArchiveUpdates.CATALOG_ACTIVE.get()) shell.post(this::startCatalogDownload);
    if (required && getIntent().getBooleanExtra(EXTRA_AUTO_START, false) && !installerPending) shell.post(this::startDownload);
  }

  // AppShield's 20 supported languages: device-locale copy falls back safely to English.
  private static String[] localized(Locale locale) {
    String language = locale.getLanguage();
    String region = locale.getCountry();
    if ("zh".equals(language) && ("TW".equals(region) || "HK".equals(region) || "MO".equals(region))) {
      return new String[]{ "有可用更新", "此應用程式可使用版本 %s。", "自動更新", "立即更新", "背景下載", "更新", "正在等待 Android 安裝程式…", "下載或驗證失敗。請再試一次。", "安裝未完成。請再試一次。", "再試一次", "正在下載並驗證更新…", "正在下載 %d %% · %s / %s MB", "正在驗證下載內容…", "有可用的新內容", "%1$s · %2$s", "下載內容", "內容已驗證。應用程式將在下次啟動時使用。", "內容受保護。請開啟封存頁面下載。", "內容下載失敗。請重試。", "開啟封存", "下載 · 驗證 · 安裝", "下載 · 驗證 · 離線就緒", "下載應用程式與內容", "完成" };
    }
    switch (language) {
      case "de": return new String[]{ "Aktualisierung verfügbar", "Version %s ist für diese App verfügbar.", "Automatisch aktualisieren", "Jetzt aktualisieren", "Im Hintergrund laden", "AKTUALISIERUNG", "Warten auf Android-Installationsprogramm…", "Download oder Überprüfung fehlgeschlagen. Versuchen Sie es erneut.", "Installation wurde nicht abgeschlossen. Versuchen Sie es erneut.", "Erneut versuchen", "Update wird heruntergeladen und überprüft…", "Download %d %% · %s / %s MB", "Download wird überprüft…", "Neue Inhalte verfügbar", "%1$s · %2$s", "Inhalte laden", "Inhalte geprüft. Die App nutzt sie beim nächsten Start.", "Inhalte sind geschützt. Öffne das Archiv, um sie zu laden.", "Inhalte konnten nicht geladen werden. Versuche es erneut.", "Archiv öffnen", "Laden · Prüfen · Installieren", "Laden · Prüfen · Offline bereit", "App + Inhalte laden", "Fertig" };
      case "es": return new String[]{ "Actualización disponible", "La versión %s está disponible para esta aplicación.", "Actualizar automáticamente", "Actualizar ahora", "Cargar en segundo plano", "ACTUALIZACIÓN", "Esperando al instalador de Android…", "La descarga o la verificación falló. Inténtalo de nuevo.", "La instalación no se completó. Inténtalo de nuevo.", "Intentar de nuevo", "Descargando y verificando la actualización…", "Descargando %d %% · %s / %s MB", "Verificando la descarga…", "Nuevo contenido disponible", "%1$s · %2$s", "Descargar contenido", "Contenido verificado. La app lo usará en el próximo inicio.", "El contenido está protegido. Abre el archivo para descargarlo.", "La descarga del contenido falló. Inténtalo de nuevo.", "Abrir archivo", "Descargar · Verificar · Instalar", "Descargar · Verificar · Listo sin conexión", "Descargar app + contenido", "Listo" };
      case "nl": return new String[]{ "Update beschikbaar", "Versie %s is beschikbaar voor deze app.", "Automatisch bijwerken", "Nu bijwerken", "Op de achtergrond laden", "UPDATE", "Wachten op het Android-installatieprogramma…", "Downloaden of verifiëren is mislukt. Probeer het opnieuw.", "De installatie is niet voltooid. Probeer het opnieuw.", "Opnieuw proberen", "De update wordt gedownload en geverifieerd…", "Downloaden %d %% · %s / %s MB", "Download wordt geverifieerd…", "Nieuwe inhoud beschikbaar", "%1$s · %2$s", "Inhoud downloaden", "Inhoud geverifieerd. De app gebruikt deze bij de volgende start.", "De inhoud is beveiligd. Open het archief om deze te downloaden.", "Downloaden van inhoud is mislukt. Probeer het opnieuw.", "Archief openen", "Downloaden · Verifiëren · Installeren", "Downloaden · Verifiëren · Offline gereed", "App + inhoud downloaden", "Klaar" };
      case "el": return new String[]{ "Διαθέσιμη ενημέρωση", "Η έκδοση %s είναι διαθέσιμη για αυτή την εφαρμογή.", "Αυτόματη ενημέρωση", "Ενημέρωση τώρα", "Λήψη στο παρασκήνιο", "ΕΝΗΜΕΡΩΣΗ", "Αναμονή για το πρόγραμμα εγκατάστασης Android…", "Η λήψη ή η επαλήθευση απέτυχε. Δοκιμάστε ξανά.", "Η εγκατάσταση δεν ολοκληρώθηκε. Δοκιμάστε ξανά.", "Δοκιμάστε ξανά", "Λήψη και επαλήθευση ενημέρωσης…", "Λήψη %d %% · %s / %s MB", "Επαλήθευση λήψης…", "Διαθέσιμο νέο περιεχόμενο", "%1$s · %2$s", "Λήψη περιεχομένου", "Το περιεχόμενο επαληθεύτηκε. Η εφαρμογή θα το χρησιμοποιήσει στην επόμενη εκκίνηση.", "Το περιεχόμενο είναι προστατευμένο. Ανοίξτε το αρχείο για λήψη.", "Η λήψη περιεχομένου απέτυχε. Δοκιμάστε ξανά.", "Άνοιγμα αρχείου", "Λήψη · Επαλήθευση · Εγκατάσταση", "Λήψη · Επαλήθευση · Έτοιμο εκτός σύνδεσης", "Λήψη εφαρμογής + περιεχομένου", "Έτοιμο" };
      case "ru": return new String[]{ "Доступно обновление", "Версия %s доступна для этого приложения.", "Обновлять автоматически", "Обновить", "Загрузить в фоне", "ОБНОВЛЕНИЕ", "Ожидание установщика Android…", "Не удалось скачать или проверить обновление. Повторите попытку.", "Установка не была завершена. Повторите попытку.", "Повторить", "Загрузка и проверка обновления…", "Загрузка %d %% · %s / %s MB", "Проверка загрузки…", "Доступен новый контент", "%1$s · %2$s", "Скачать контент", "Контент проверен. Приложение использует его при следующем запуске.", "Контент защищён. Откройте архив, чтобы скачать его.", "Не удалось скачать контент. Повторите попытку.", "Открыть архив", "Загрузка · Проверка · Установка", "Загрузка · Проверка · Готово офлайн", "Загрузить приложение и контент", "Готово" };
      case "ja": return new String[]{ "アップデートがあります", "このアプリ用のバージョン %s が利用できます。", "自動更新", "今すぐ更新", "バックグラウンドでダウンロード", "アップデート", "Android のインストーラーを待機しています…", "ダウンロードまたは検証に失敗しました。もう一度お試しください。", "インストールが完了しませんでした。もう一度お試しください。", "再試行", "アップデートをダウンロードして検証しています…", "ダウンロード中 %d %% · %s / %s MB", "ダウンロードを検証しています…", "新しいコンテンツがあります", "%1$s · %2$s", "コンテンツをダウンロード", "コンテンツを検証しました。次回起動時にアプリが使用します。", "コンテンツは保護されています。アーカイブを開いてダウンロードしてください。", "コンテンツのダウンロードに失敗しました。もう一度お試しください。", "アーカイブを開く", "ダウンロード · 検証 · インストール", "ダウンロード · 検証 · オフライン準備完了", "アプリとコンテンツをダウンロード", "完了" };
      case "fr": return new String[]{ "Mise à jour disponible", "La version %s est disponible pour cette application.", "Mise à jour automatique", "Mettre à jour", "Télécharger en arrière-plan", "MISE À JOUR", "En attente du programme d’installation Android…", "Échec du téléchargement ou de la vérification. Réessayez.", "L’installation n’a pas été effectuée. Réessayez.", "Réessayer", "Téléchargement et vérification de la mise à jour…", "Téléchargement %d %% · %s / %s MB", "Vérification du téléchargement…", "Nouveau contenu disponible", "%1$s · %2$s", "Télécharger le contenu", "Contenu vérifié. L’app l’utilisera au prochain démarrage.", "Le contenu est protégé. Ouvrez l’archive pour le télécharger.", "Échec du téléchargement du contenu. Réessayez.", "Ouvrir l’archive", "Télécharger · Vérifier · Installer", "Télécharger · Vérifier · Prêt hors ligne", "Télécharger l’app et le contenu", "Terminé" };
      case "it": return new String[]{ "Aggiornamento disponibile", "La versione %s è disponibile per questa app.", "Aggiorna automaticamente", "Aggiorna ora", "Scarica in background", "AGGIORNAMENTO", "In attesa del programma di installazione Android…", "Download o verifica non riusciti. Riprova.", "L’installazione non è stata completata. Riprova.", "Riprova", "Download e verifica dell’aggiornamento…", "Download %d %% · %s / %s MB", "Verifica del download…", "Nuovo contenuto disponibile", "%1$s · %2$s", "Scarica contenuto", "Contenuto verificato. L’app lo userà al prossimo avvio.", "Il contenuto è protetto. Apri l’archivio per scaricarlo.", "Download del contenuto non riuscito. Riprova.", "Apri archivio", "Scarica · Verifica · Installa", "Scarica · Verifica · Pronto offline", "Scarica app e contenuti", "Fatto" };
      case "pt": return new String[]{ "Atualização disponível", "A versão %s está disponível para este app.", "Atualizar automaticamente", "Atualizar agora", "Baixar em segundo plano", "ATUALIZAÇÃO", "Aguardando o instalador do Android…", "Falha no download ou na verificação. Tente novamente.", "A instalação não foi concluída. Tente novamente.", "Tentar novamente", "Baixando e verificando a atualização…", "Baixando %d %% · %s / %s MB", "Verificando o download…", "Novo conteúdo disponível", "%1$s · %2$s", "Baixar conteúdo", "Conteúdo verificado. O app usará na próxima inicialização.", "O conteúdo é protegido. Abra o arquivo para baixá-lo.", "Falha no download do conteúdo. Tente novamente.", "Abrir arquivo", "Baixar · Verificar · Instalar", "Baixar · Verificar · Pronto offline", "Baixar app + conteúdo", "Concluído" };
      case "pl": return new String[]{ "Dostępna aktualizacja", "Wersja %s jest dostępna dla tej aplikacji.", "Aktualizuj automatycznie", "Aktualizuj teraz", "Pobierz w tle", "AKTUALIZACJA", "Oczekiwanie na instalator Androida…", "Pobieranie lub weryfikacja nie powiodły się. Spróbuj ponownie.", "Instalacja nie została ukończona. Spróbuj ponownie.", "Spróbuj ponownie", "Pobieranie i weryfikowanie aktualizacji…", "Pobieranie %d %% · %s / %s MB", "Weryfikowanie pobrania…", "Dostępna nowa zawartość", "%1$s · %2$s", "Pobierz zawartość", "Zawartość zweryfikowana. Aplikacja użyje jej przy następnym uruchomieniu.", "Zawartość jest chroniona. Otwórz archiwum, aby ją pobrać.", "Pobieranie zawartości nie powiodło się. Spróbuj ponownie.", "Otwórz archiwum", "Pobierz · Zweryfikuj · Zainstaluj", "Pobierz · Zweryfikuj · Gotowe offline", "Pobierz aplikację i zawartość", "Gotowe" };
      case "cs": return new String[]{ "Aktualizace je k dispozici", "Verze %s je pro tuto aplikaci k dispozici.", "Aktualizovat automaticky", "Aktualizovat", "Stáhnout na pozadí", "AKTUALIZACE", "Čeká se na instalační program Androidu…", "Stažení nebo ověření se nezdařilo. Zkuste to znovu.", "Instalace nebyla dokončena. Zkuste to znovu.", "Zkusit znovu", "Stahování a ověřování aktualizace…", "Stahování %d %% · %s / %s MB", "Ověřování stažení…", "Je k dispozici nový obsah", "%1$s · %2$s", "Stáhnout obsah", "Obsah ověřen. Aplikace jej použije při příštím spuštění.", "Obsah je chráněný. Otevřete archiv a stáhněte jej.", "Stažení obsahu se nezdařilo. Zkuste to znovu.", "Otevřít archiv", "Stáhnout · Ověřit · Nainstalovat", "Stáhnout · Ověřit · Připraveno offline", "Stáhnout aplikaci a obsah", "Hotovo" };
      case "uk": return new String[]{ "Доступне оновлення", "Версія %s доступна для цього застосунку.", "Оновлювати автоматично", "Оновити", "Завантажити у фоні", "ОНОВЛЕННЯ", "Очікування інсталятора Android…", "Не вдалося завантажити або перевірити оновлення. Спробуйте ще раз.", "Встановлення не завершено. Спробуйте ще раз.", "Спробувати ще раз", "Завантаження та перевірка оновлення…", "Завантаження %d %% · %s / %s MB", "Перевірка завантаження…", "Доступний новий вміст", "%1$s · %2$s", "Завантажити вміст", "Вміст перевірено. Застосунок використає його під час наступного запуску.", "Вміст захищено. Відкрийте архів, щоб завантажити його.", "Не вдалося завантажити вміст. Спробуйте ще раз.", "Відкрити архів", "Завантаження · Перевірка · Встановлення", "Завантаження · Перевірка · Готово офлайн", "Завантажити застосунок і вміст", "Готово" };
      case "tr": return new String[]{ "Güncelleme hazır", "%s sürümü bu uygulama için hazır.", "Otomatik güncelle", "Şimdi güncelle", "Arka planda indir", "GÜNCELLEME", "Android yükleyicisi bekleniyor…", "İndirme veya doğrulama başarısız oldu. Tekrar deneyin.", "Yükleme tamamlanmadı. Tekrar deneyin.", "Tekrar dene", "Güncelleme indiriliyor ve doğrulanıyor…", "İndiriliyor %d %% · %s / %s MB", "İndirme doğrulanıyor…", "Yeni içerik hazır", "%1$s · %2$s", "İçeriği indir", "İçerik doğrulandı. Uygulama bir sonraki açılışta kullanacak.", "İçerik korumalı. İndirmek için arşivi açın.", "İçerik indirilemedi. Tekrar deneyin.", "Arşivi aç", "İndir · Doğrula · Yükle", "İndir · Doğrula · Çevrimdışı hazır", "Uygulama + içerik indir", "Bitti" };
      case "ar": return new String[]{ "يتوفر تحديث", "الإصدار %s متاح لهذا التطبيق.", "التحديث تلقائيًا", "التحديث الآن", "التنزيل في الخلفية", "تحديث", "في انتظار مُثبّت Android…", "فشل التنزيل أو التحقق. حاول مرة أخرى.", "لم يكتمل التثبيت. حاول مرة أخرى.", "حاول مرة أخرى", "جارٍ تنزيل التحديث والتحقق منه…", "جارٍ التنزيل %d %% · %s / %s MB", "جارٍ التحقق من التنزيل…", "محتوى جديد متاح", "%1$s · %2$s", "تنزيل المحتوى", "تم التحقق من المحتوى. سيستخدمه التطبيق عند التشغيل التالي.", "المحتوى محمي. افتح الأرشيف لتنزيله.", "فشل تنزيل المحتوى. حاول مرة أخرى.", "فتح الأرشيف", "تنزيل · تحقق · تثبيت", "تنزيل · تحقق · جاهز دون اتصال", "تنزيل التطبيق والمحتوى", "تم" };
      case "hi": return new String[]{ "अपडेट उपलब्ध है", "इस ऐप के लिए संस्करण %s उपलब्ध है।", "अपने-आप अपडेट करें", "अभी अपडेट करें", "पृष्ठभूमि में डाउनलोड करें", "अपडेट", "Android इंस्टॉलर की प्रतीक्षा की जा रही है…", "डाउनलोड या पुष्टि नहीं हो सकी। फिर से कोशिश करें।", "इंस्टॉलेशन पूरा नहीं हुआ। फिर से कोशिश करें।", "फिर से कोशिश करें", "अपडेट डाउनलोड और सत्यापित किया जा रहा है…", "डाउनलोड %d %% · %s / %s MB", "डाउनलोड की पुष्टि हो रही है…", "नई सामग्री उपलब्ध है", "%1$s · %2$s", "सामग्री डाउनलोड करें", "सामग्री सत्यापित। ऐप इसे अगली बार खुलने पर उपयोग करेगा।", "सामग्री सुरक्षित है। डाउनलोड करने के लिए संग्रह खोलें।", "सामग्री डाउनलोड नहीं हो सकी। फिर से कोशिश करें।", "संग्रह खोलें", "डाउनलोड · सत्यापन · इंस्टॉल", "डाउनलोड · सत्यापन · ऑफ़लाइन तैयार", "ऐप + सामग्री डाउनलोड करें", "पूर्ण" };
      case "id": return new String[]{ "Pembaruan tersedia", "Versi %s tersedia untuk aplikasi ini.", "Perbarui otomatis", "Perbarui sekarang", "Unduh di latar belakang", "PEMBARUAN", "Menunggu penginstal Android…", "Pengunduhan atau verifikasi gagal. Coba lagi.", "Penginstalan tidak selesai. Coba lagi.", "Coba lagi", "Mengunduh dan memverifikasi pembaruan…", "Mengunduh %d %% · %s / %s MB", "Memverifikasi unduhan…", "Konten baru tersedia", "%1$s · %2$s", "Unduh konten", "Konten terverifikasi. Aplikasi akan memakainya saat mulai berikutnya.", "Konten dilindungi. Buka arsip untuk mengunduhnya.", "Pengunduhan konten gagal. Coba lagi.", "Buka arsip", "Unduh · Verifikasi · Pasang", "Unduh · Verifikasi · Siap offline", "Unduh aplikasi + konten", "Selesai" };
      case "sv": return new String[]{ "Uppdatering tillgänglig", "Version %s är tillgänglig för den här appen.", "Uppdatera automatiskt", "Uppdatera nu", "Hämta i bakgrunden", "UPPDATERING", "Väntar på Android-installationsprogrammet…", "Det gick inte att hämta eller verifiera. Försök igen.", "Installationen slutfördes inte. Försök igen.", "Försök igen", "Hämtar och verifierar uppdateringen…", "Hämtar %d %% · %s / %s MB", "Verifierar hämtningen…", "Nytt innehåll tillgängligt", "%1$s · %2$s", "Hämta innehåll", "Innehåll verifierat. Appen använder det vid nästa start.", "Innehållet är skyddat. Öppna arkivet för att hämta det.", "Det gick inte att hämta innehållet. Försök igen.", "Öppna arkivet", "Hämta · Verifiera · Installera", "Hämta · Verifiera · Klar offline", "Hämta app + innehåll", "Klart" };
      case "ko": return new String[]{ "업데이트가 있습니다", "이 앱에 버전 %s을(를) 사용할 수 있습니다.", "자동 업데이트", "지금 업데이트", "백그라운드에서 다운로드", "업데이트", "Android 설치 프로그램을 기다리는 중…", "다운로드 또는 확인에 실패했습니다. 다시 시도하세요.", "설치가 완료되지 않았습니다. 다시 시도하세요.", "다시 시도", "업데이트를 다운로드하고 확인하는 중…", "다운로드 중 %d %% · %s / %s MB", "다운로드를 확인하는 중…", "새 콘텐츠가 있습니다", "%1$s · %2$s", "콘텐츠 다운로드", "콘텐츠를 확인했습니다. 다음 실행 시 앱이 사용합니다.", "콘텐츠가 보호되어 있습니다. 아카이브를 열어 다운로드하세요.", "콘텐츠 다운로드에 실패했습니다. 다시 시도하세요.", "아카이브 열기", "다운로드 · 확인 · 설치", "다운로드 · 확인 · 오프라인 준비 완료", "앱 + 콘텐츠 다운로드", "완료" };
      case "zh": return new String[]{ "有可用更新", "此应用可使用版本 %s。", "自动更新", "立即更新", "后台下载", "更新", "正在等待 Android 安装程序…", "下载或验证失败。请重试。", "安装未完成。请重试。", "重试", "正在下载并验证更新…", "正在下载 %d %% · %s / %s MB", "正在验证下载…", "有可用的新内容", "%1$s · %2$s", "下载内容", "内容已验证。应用将在下次启动时使用。", "内容受保护。请打开归档页面下载。", "内容下载失败。请重试。", "打开归档", "下载 · 校验 · 安装", "下载 · 校验 · 离线就绪", "下载应用和内容", "完成" };
      default: return new String[]{ "Update available", "Version %s is available for this app.", "Update automatically", "Update now", "Load in background", "UPDATE", "Waiting for Android installer…", "Download or verification failed. Try again.", "Installation was not completed. Try again.", "Try again", "Downloading and verifying update…", "Downloading %d %% · %s / %s MB", "Verifying download…", "New content available", "%1$s · %2$s", "Download content", "Content verified. The app will use it on next start.", "Content is protected. Open the archive to download it.", "Content download failed. Try again.", "Open archive", "Download · Verify · Install", "Download · Verify · Ready offline", "Download app + content", "Done" };
    }
  }

  private TextView primaryButton(String value) { TextView view = text(value, 15, contrastOnAccent(), true); view.setGravity(Gravity.CENTER); view.setMaxLines(2); view.setPadding(dp(12), 0, dp(12), 0); view.setBackground(round(accent, 15)); tactile(view); return view; }
  private TextView secondaryButton(String value) { TextView view = text(value, 14, accentInk, true); view.setGravity(Gravity.CENTER); view.setMaxLines(2); view.setPadding(dp(12), 0, dp(12), 0); GradientDrawable background = round(Color.TRANSPARENT, 15); background.setStroke(dp(1), Color.argb(168, Color.red(accentInk), Color.green(accentInk), Color.blue(accentInk))); view.setBackground(background); tactile(view); return view; }
  @SuppressLint("ClickableViewAccessibility")
  private void tactile(TextView view) {
    view.setFocusable(true); view.setClickable(true);
    view.setOnTouchListener((target, event) -> {
      if (!target.isEnabled()) return false;
      boolean pressed = event.getActionMasked() == android.view.MotionEvent.ACTION_DOWN;
      target.animate().scaleX(pressed ? .98f : 1f).scaleY(pressed ? .98f : 1f).setDuration(120).start();
      return false;
    });
  }
  private int contrastOnAccent() { double luminance = luminance(accent); return luminance > .56d ? Color.rgb(12, 14, 18) : Color.WHITE; }
  private TextView text(String value, int sp, int color, boolean bold) { TextView view = new TextView(this); view.setText(value); view.setTextSize(sp); view.setTextColor(color); view.setGravity(Gravity.START); view.setTextDirection(View.TEXT_DIRECTION_LOCALE); if (bold) view.setTypeface(Typeface.DEFAULT_BOLD); return view; }
  private GradientDrawable round(int color, int radius) { GradientDrawable shape = new GradientDrawable(); shape.setColor(color); shape.setCornerRadius(dp(radius)); return shape; }
  // The card carries a hairline of the host's own brand so it reads as one of the
  // app's surfaces instead of a floating panel from somewhere else.
  private GradientDrawable card(int color, int radius) { GradientDrawable shape = round(color, radius); shape.setStroke(dp(1), Color.argb(46, Color.red(accentInk), Color.green(accentInk), Color.blue(accentInk))); return shape; }
  private int dp(int value) { return (int) (value * getResources().getDisplayMetrics().density + .5f); }
}
